# Strings

In [2]:
my_str = 'Hello'
my_str2 = "hello"
my_str3 = """hello"""
print(my_str,my_str2,my_str3)

Hello hello hello


In [3]:
my_str = input("Enter your name:")
print(my_str)

Enter your name: jatin asip


jatin asip


# string slicing

In [20]:
my_str = "hello, ready to explore python!!"
#[starting pnt : ending : step]
print(my_str[4:16:2])# o ed o
print(my_str[12:30])# to explore python
print(my_str[:10])#0-9 index will execute.
print(my_str[::-1])
print(my_str.split(' '))
print(my_str.split('o'))

print(my_str.split('l'))

o ed o
 to explore python
hello, rea
!!nohtyp erolpxe ot ydaer ,olleh
['hello,', 'ready', 'to', 'explore', 'python!!']
['hell', ', ready t', ' expl', 're pyth', 'n!!']
['he', '', 'o, ready to exp', 'ore python!!']


WAP to count the number of words in a given string

In [36]:
my_str = "how are you jatin"
space_count = 1
for i in my_str:
    if (i== " "):
     space_count +=1  
print(f"The number of words are:{space_count}")


The number of words are:4


In [39]:
# my_str = "how are you jatin"
# my_str2 = my_str.split(' ')
# my_set = set(my_str2)
# space_count = 1
# for i in my_set:
    
#      space_count +=1  
# print(f"The number of words are:{space_count}")


The number of words are:5


2. WAP to reverse a given string withoyut using slicing or inbuilt techniques.
3. METHOD =1

In [55]:
my_str = input("Enter the string:")
n = len(my_str)
print(type(my_str))
rev_str = ""
for i in range(n-1,-1,-1):
    rev_str += my_str[i]
print(rev_str)   
print(type(rev_str))   

print("DONE")
    

Enter the string: Jatin


<class 'str'>
nitaJ
<class 'str'>
DONE


In [1]:
my_str = "Python"
my_list = list(my_str)
i = 0
j = len(my_str)-1
while(i<=j):
   my_list[i],my_list[j] = my_list[j],my_list[i]
   i+=1
   j-=1
# rev_str = str(my_list)
# print(rev_str)
print(str(my_list))
    

['n', 'o', 'h', 't', 'y', 'P']


WAP to count the number of duplicates in a given string.


In [72]:
str1 = "Python Programming"
count = 0
for j in str1:
    for i in str1:
            if(j==i):
              count+=1
print(f"No. of duplicates:{count-len(str1)}")

No. of duplicates:12


In [74]:
str1 = "Python Programming"
count = 0
for i in range(0,len(str1)):
    for j in range(0,len(str1)):
        if(i==j):
            continue
        elif(str1[i]==str1[j]):
            count +=1
print(f"The no. of duplicates are:{count}")

The no. of duplicates are:12


In [75]:
str1 = "python programming"
count = 0
for i in range(0,len(str1)):
    for j in range(i+1,len(str1)):
        if (str1[i]==str1[j]):
            count +=1
print(count)

6


QUESTIONS:-
1. WAP to check a string is palindrome or not
2. WAP to check a string is anagram or not.

In [76]:
%whos

Variable      Type    Data/Info
-------------------------------
a             int     5
count         int     6
i             int     17
j             int     17
list1         list    n=8
my_list       list    n=6
my_set        set     {'you', 'jatin', 'how', 'are'}
my_str        str     Python
my_str2       list    n=4
my_str3       str     hello
n             int     5
rev_str       str     ['n', 'o', 'h', 't', 'y', 'P']
space_count   int     5
str1          str     python programming


* Palindrome number

In [2]:
str = input("Enter the string:")
rev_str = ""
n = len(str)
for i in range(n-1,-1,-1):
    rev_str += str[i]
if(rev_str == str):
    print(f"The string is Palindrome.")
else:
    print(f"The string is not Palindrome.")

Enter the string: madam


The string is Palindrome.


# Lists

In [4]:
x = [19,10.5,False,"python",(4+3j)]
x.append(45)
print(x)
print(type(x))

[19, 10.5, False, 'python', (4+3j), 45]
<class 'list'>


Functions in List.

In [17]:
#ADDING ELEMENTS IN LIST USING THREE DIFFERENT FUNCTIONS.
lst = [10,20,30]
#using append function--> add the element at the end of list.
print("Before append function:",lst)
lst.append(40)
lst.append(50)
print("After append function.",lst) 
#using insert function--> add the element at the given position.
lst.insert(2,60)
print("After insert function.",lst)
#using extend function-->adds iterables
lst1 = [70,80,90]
lst.extend(lst1)
print("After using extend function.",lst)

Before append function: [10, 20, 30]
After append function. [10, 20, 30, 40, 50]
After insert function. [10, 20, 60, 30, 40, 50]
After using extend function. [10, 20, 60, 30, 40, 50, 70, 80, 90]


Functions to remove the data from list

In [27]:
lst = [10,20,30,40,50,50,60,70]
print("Before delete function:",lst)
#using remove function--> Delete the specific element.
lst.remove(50)
print("After remove function:",lst)

#using pop()--> deletes the data from the end.
lst.pop()
print("After pop function:",lst)

#using clear()--> delete all the data from list.
lst.clear()
print("List after clear function",lst)

Before delete function: [10, 20, 30, 40, 50, 50, 60, 70]
After remove function: [10, 20, 30, 40, 50, 60, 70]
After pop function: [10, 20, 30, 40, 50, 60]
List after clear function []


More important Functions for arranging the list.

In [35]:
lst = [1,4,53,6,3,9]
print("Before sorting:",lst)

#using sort()--> used to sort the list in increasing order.
lst.sort()
print("After sorting:",lst)

#using reverse ()--> used to reverse the list.
lst.reverse()
print("After reverse function",lst)

Before sorting: [1, 4, 53, 6, 3, 9]
After sorting: [1, 3, 4, 6, 9, 53]
After reverse function [53, 9, 6, 4, 3, 1]


In [38]:
lst = [1,1,1,1,1,1,2,2,2,3,4,5,6,1,2]
print(lst.count(1)) # gives the freq of any specific number.
print(lst.count(2))
print(lst.count(3))
print(lst.count(4))
print(lst.count(5))

7
4
1
1
1


Taking list from user

In [44]:
#WAP to create a list.
size = int(input("Enter the size of the list:"))
lst = []
for i in range(size):
    elem = int(input("Enter the element:"))
    lst.append(elem)
print(lst)

Enter the size of the list: 5
Enter the element: 1
Enter the element: 2
Enter the element: 3
Enter the element: 4
Enter the element: 5


[1, 2, 3, 4, 5]


In [57]:
#WAP to create a 2D list.
row = int(input("Enter the row size:"))
col = int(input("Enter the column size:"))
lst = [[i for i in range(5)]]
for i in range(row):
    for j in range(col):
        ele = int(input("Enter the element:"))
        lst.append(ele)
print(lst)

Enter the row size: 2
Enter the column size: 3
Enter the element: 1
Enter the element: 2
Enter the element: 3
Enter the element: 4
Enter the element: 5
Enter the element: 6


[[0, 1, 2, 3, 4], 1, 2, 3, 4, 5, 6]


1. WAP to FIND THE LENGTH OF THE GIVEN LIST.

In [62]:
lst = [1,2,3,4,5,6]
# n = len(lst)
count = 0
for i in lst:
    count +=1
print(count)

6


2. WAP to calculate the sum of all the elements in the list.


In [64]:
size = int(input("Enter the size of list:"))
lst =[]
sum = 0
for i in range(size):
    ele = int(input("Enter the elements:"))
    lst.append(ele)
#Approach 1:
for j in lst:
    sum = sum + j
print(sum)

Enter the size of list: 5
Enter the elements: 2
Enter the elements: 3
Enter the elements: 4
Enter the elements: 1
Enter the elements: 2


12


SETS IN PYTHON

In [74]:
#ADD AND UPDATE FUNCTION.
set1 = {1,2,3,4,5,6}
print("Before add method:",set1)
#using add method--> 
set1.add(10)
print("After add method:",set1)

#Using update()--> adds iterable.
set2 = {20,21,22}
set1.update(set2)
print("After update function:",set1)

Before add method: {1, 2, 3, 4, 5, 6}
After add method: {1, 2, 3, 4, 5, 6, 10}
After update function: {1, 2, 3, 4, 5, 6, 10, 20, 21, 22}


In [75]:
set1 = {1,1,2,2,3,4,3,1,1,2}
print(set1)
#there can be no duplicates.

{1, 2, 3, 4}


In [76]:
set1 = {1,4,2,5,7,9}
print(set1)
#always gives data in sorted order.

{1, 2, 4, 5, 7, 9}


In [81]:
set1 = {1,5,8,9,3,4}

set1.remove(8)
print(set1)

set1.discard(3)
print(set1)

set1.clear()
print(set1)

{1, 3, 4, 5, 9}
{1, 4, 5, 9}
set()


In [92]:
set1 = {1,2,3,4}
set2 = {3,4,5,6,7}
set1.union(set2)

{1, 2, 3, 4, 5, 6, 7}

In [93]:
set1.difference(set2)

{1, 2}

In [94]:
set1.symmetric_difference(set2)

{1, 2, 5, 6, 7}

In [95]:
set1.intersection(set2)

{3, 4}

1. [ ]--> list
2. { }-->Dictionary
3. ( )--> tuple

In [99]:
size = int(input("Enter the size:"))
my_set = set()
for i in range(size):
    ele = int(input("Enter the elements :"))
    my_set.add(ele)
print(my_set)

Enter the size: 5
Enter the elements : 2
Enter the elements : 3
Enter the elements : 1
Enter the elements : 6
Enter the elements : 3


{1, 2, 3, 6}


3. WAP to remove all occurance of a specific elements.

In [126]:
size = int(input("Enter the size:")) 

lst=[]
new_lst=[]
for i in range(size):
    ele = int(input("Enter the element:"))
    lst.append(ele)
    
key = int(input("Enter the element to be removed"))
for i in lst:
    if (key!=i):
        new_lst.append(i)
print(new_lst)

Enter the size: 4
Enter the element: 1
Enter the element: 2
Enter the element: 3
Enter the element: 4
Enter the element to be removed 3


[1, 2, 4]


4. WAP when given 2 lists find the common elements in btw.

In [127]:
lst1 = [2,3,4,5,6,1]
lst2 = [3,4,6,7,9,8,2,10]
newlst = []
for i in lst1:
    for j in lst2:
        if(i==j):
          newlst.append(j)
print(newlst)

[2, 3, 4, 6]


5. WAP where you have given a list of words count the freq of each word

In [26]:
lst = ["apple","is","red","an","apple","a","day","keeps","doctor","away"]
j=1
while(j<len(lst)):
    count = 1
   
    for i in range(j+1,len(lst)):
      if(lst[j]==lst[i]):
         count += 1
    print(lst[j]," ",count)
    j+=1


is   1
red   1
an   1
apple   1
a   1
day   1
keeps   1
doctor   1
away   1


* ANAGRAM PROBLEM

In [25]:
#USING LIST METHOD.
word1 = input("Enter the first word: ")
word2 = input("Enter the second word: ")


new1 = list(word1)
new2 = list(word2)
new1.sort()
new2.sort()

# print(new1)
# print(new2)
if new1 == new2:

    print(f"The words {word1} and {word2} are anagrams.")
else:
     print(f"The words {word1} and {word2} are not anagrams.")


Enter the first word:  ujra
Enter the second word:  uajr


The words ujra and uajr are anagrams.


In [16]:
word1 = input("Enter the first word:")
word2 = input("Enter the second word:")
newWord1 = sorted(word1)
newWord2 = sorted(word2)
if newWord1 == newWord2:
    print(f"The words {word1} and {word2} are anagrams.")
else:
    
    print(f"The words {word1} and {word2} are not anagrams.")

Enter the first word: urja
Enter the second word: raju


The words urja and raju are anagrams.


# OOP's in Python

In [2]:
#Rule for defining a class.
#class ClassName:
class Student:
     clg = "Global"
     

In [3]:
class Car:
    wheels = 4
    
    def __init__(self,color):
      print("The address from self:",self)
      self.color = color
    def disp(self):
        print(self.color)

c1 = Car("black")
print("Address from object",c1)
c2 = Car("Chocolate")
print("Address from",c2)
print(c1.wheels)
c1.disp()
print(c2.wheels)
c2.disp()

The address from self: <__main__.Car object at 0x0000022D3D76F950>
Address from object <__main__.Car object at 0x0000022D3D76F950>
The address from self: <__main__.Car object at 0x0000022D3D76FDD0>
Address from <__main__.Car object at 0x0000022D3D76FDD0>
4
black
4
Chocolate


* WAP to create a class student with attributes id,name,college and display all the attributes of the particular student details.

In [35]:
class Student:
    def __init__(self,name,id,clg):
        self.name = name
        self.id = id
        self.clg = clg
        
    def disp(self):
            print("The name of student is:",self.name)
            print("The id of student is:",self.id)
            print("The college of student is:",self.clg)
s1 = Student("Raju",2,"global")
s2 = Student("shubhi",3,"global")
s3 = Student("vedant",4,"global")
s4 = Student("cheenu",5,"global")
s5 = Student("jatin",6,"global")
s1.disp()
s2.disp()
s3.disp()
s4.disp()
s5.disp()

The name of student is: Raju
The id of student is: 2
The college of student is: global
The name of student is: shubhi
The id of student is: 3
The college of student is: global
The name of student is: vedant
The id of student is: 4
The college of student is: global
The name of student is: cheenu
The id of student is: 5
The college of student is: global
The name of student is: jatin
The id of student is: 6
The college of student is: global


WAP to create a class Animal with properties type,color,num of legs,to disp its behaviour eats,walk,sleep

In [37]:
class Animal:
    def __init__(self,type,color):
        self.type = type
        self.color = color

    def disp(self):
        print("The type is:",self.type)
        print("The color is:",self.color)
        
tiger = Animal("Carnivore","yellow")
dog = Animal("Omnivores","white")
dog.disp()
tiger.disp()

The type is: Omnivores
The color is: white
The type is: Carnivore
The color is: yellow


Inheritence in python

In [40]:
class A:  
    def disp(self):
        print("Display A")

class B(A):

    pass

objB = B()
objB.disp()
objA = A()
objA.disp()

Display A
Display A


In [44]:
class GrandFather:
    def property(self):
        print("cash+land+gold")

class Father(GrandFather):
    pass


class Son(Father):
    pass


class GrandSon():
    pass
    
s = Son()
s.property()
f = Father()
f.property()
gf = GrandFather()
gf.property()
gs = GrandSon()
gs.property()

cash+land+gold
cash+land+gold
cash+land+gold


* Multilevel Inheritence

In [53]:
class Animal:
    def eat(self):
        print("Eating")
class Cow(Animal):
    def walk(self):
        print("Cow is walking")
class Tiger(Animal):
    def run(self):
        print("Tiger Running")

class Bear(Animal):
    def sleep(self):
        print("Bear sleeping")
c = Cow()
c.eat()
c.walk()

Eating
Cow is walking


* Multiple Inheritence

In [56]:
class Animal:
    def eat(self):
        print("Eating")

class Bird:
    def fly(self):
        print("Flying")

class X(Animal,Bird):
    pass

x1 = X()
x1.fly()
x1.eat()


Flying
Eating


* Method OverRiding

In [58]:
class Parent:
    def property(self):
        print("cash+land+gold")
    def marry(self):
        print("Trisha")

class Child(Parent):
    def marry(self):
        print("Sam")

c = Child()
c.property()
c.marry()

cash+land+gold
Sam


* Encapsulation

In [63]:
class Bank:
    def __init__(self,balance):
        self.__balance = balance  #_ using this it became protected.
        #__ defines private.

objBank = Bank(1000)
print(objBank.balance)

AttributeError: 'Bank' object has no attribute 'balance'

In [ ]:
def disp(x):
    for i in range(x):
        return i

print(disp(5))

In [67]:
def disp(start,end):
    for i in range(start,end+1):
        print(i)
    pass
disp(11,16)

11
12
13
14
15
16


In [1]:
# def disp(*args) 
#taking multiple args as input.
#def __del__() destructor

WAP to create a class Animal with properties type,color,num of legs,to disp its behaviour eats,walk,sleep

In [8]:
class Animal:
    def __init__(self,type,color):
        self.type = type
        self.color = color

    def disp(self):
        print("The type is:",self.type)
        print("The color is:",self.color)
    
class Dog(Animal):
    def eat(self):
     print("the dog Is eating Biscuit.")
    def walk(self):
        print("The dog is walking.")

class tiger(Animal):
    def eat(self):
     print("the tiger Is eating Flesh.")
    def run(self):
        print("The tiger is running")

t = tiger(Animal,'Yellow')
t.disp()
t.eat()
t.run()
d = Dog(Animal,'White')
d.disp()
d.eat()
d.walk()


The type is: <class '__main__.Animal'>
The color is: Yellow
the tiger Is eating Flesh.
The tiger is running
The type is: <class '__main__.Animal'>
The color is: White
the dog Is eating Biscuit.
The dog is walking.


1. Bank Account System - You are designing a bank account management system. Each account has an account holder's name,balance, and account type (Savings/Current)
2. Use inheritance to create a SavingsAccount and CurrentAccount class from a common BankAccount class.
Implement polymorphism for a method calculate_interest() that computes interest differently for savings and current accounts.
Ensure account numbers are unique for each object using a class attribute.
Can you write a program to demonstrate this?

In [12]:
class Bank:
   
    def __init__(self,name,bal,accType):
        self.name = name
        self.bal = bal
        self.accType = accType
        
    def disp(self):
        print(f"The name of candidate is:",self.name)
        print(f"The Balance of candidate is:",self.bal)
        print(f"The Account Type of candidate is:",self.accType)
    
    def Calculate_Interest(self,prin,time,rate):
           # Interest = P * R * T, 
            self.prin = prin
            self.time = time
            self.rate = rate
            self.Int = Int
            Int = prin*rate*time
            print(f"The Interest calculated is:{Int}")
c1 = Bank("Jatin",45700000,"Savings")
c1.disp()
c1.Calculate_Interest(1000,5,4)

The name of candidate is: Jatin
The Balance of candidate is: 45700000
The Account Type of candidate is: Savings


UnboundLocalError: cannot access local variable 'Int' where it is not associated with a value

In [15]:
def add(x,y):
    return x+y
def add(x,y,z):
    return x+y+z
res = add(5,6,1)
print(res)

12


In [17]:
def add(*args):
    res = 0
    for i in args:
        res += i
    return res

finalValue = add(3,4,5,6,1)
print(finalValue)

19


In [19]:
def add(*args):
    res = 0
    for i in args:
        res += i
    return res

finalValue = add(3,4,5,6,1)
print(finalValue)

19


In [24]:
def Student(**kwargs):
    for name,id in kwargs.items():
      print(f"{name}:{id}")

s1 = Student(name = "Ramu",id = 4)
s2 = Student(id = 5,name = "Raj")
# s3 = Student("uvaish",8)

name:Ramu
id:4
id:5
name:Raj


# Lambda Function

In [31]:
res = lambda x,y:x*y
print(res(3,4))

12


In [32]:
even = lambda num:num%2 == 0
print(even(23))

False


WAP to find product of 4 numbers and check whether the result is multiple of 5 or not.

In [37]:
pro = lambda a,b,c,d:a*b*c*d
d = pro(1,5,2,1)
chk = lambda d:d%5==0
print(d)
print(chk(d))

10
True


In [39]:
def add(x,y,operation):
    return operation(x,y)

res = add(5,6,lambda x,y:x+y)
print(res)
    

11


In [40]:
def add(x,y,operation1,operation2):
    return operation1(x,y),operation2(x,y)

res = add(5,6,lambda x,y:x+y,lambda x,y:x*y)
print(res)
    

(11, 30)


create a function that has 2 function in it even and odd return the o/p for a number in form of tuples.

In [43]:
def Number(x,even,odd):
    return even(x),odd(x)

res = Number(24,lambda x:x%2==0,lambda x:x%2!=0)
print(res)

(True, False)


In [45]:
my_lst = [1,2,3,4]
my_lst2 = list(map(lambda x:x**2,my_lst))
print(my_lst2)

[1, 4, 9, 16]


WAP a program to create a list of 5 numbers and return their remainders after dividing it by 2 in form of list.

In [56]:
size = int(input("Enter the size of list:"))
lst = []
for i in range(size):
    ele = int(input(f"Enter the {i}th elements of list:"))
    lst.append(ele)

lst2 = list(map(lambda x:x%2,lst))
print(lst2)

Enter the size of list: 2
Enter the 0th elements of list: 23
Enter the 1th elements of list: 45


[1, 1]


In [54]:
lst = [1,2,3,4]
lst2 = list(filter(lambda x:x%2==0,lst))
lst2

[2, 4]

In [55]:
size = int(input("Enter the size of list:"))
lst = []
for i in range(size):
    ele = int(input(f"Enter the {i}th elements of list:"))
    lst.append(ele)

lst2 = list(filter(lambda x:x%3==0,lst))
lst2

Enter the size of list: 5
Enter the 0th elements of list: 12
Enter the 1th elements of list: 23
Enter the 2th elements of list: 33
Enter the 3th elements of list: 42
Enter the 4th elements of list: 66


[12, 33, 42, 66]

In [58]:
from functools import reduce
lst = [1,2,3,4,5]
lst2 = reduce(lambda x,y:x*y,lst)
lst2

120

# Generator in python


In [61]:
def disp(x):
    for i in range(1,x+1):
        yield i

res = disp(5)
print(next(res))
print(next(res))
print(next(res))
print(next(res))

1
2
3
4


In [66]:
def even(n):
    for i in range(1,n+1):
        if(i%2==0):
            yield i
res = even(10)

for i in even(10):
    print(i)

2
4
6
8
10


# Most important concept of python Regular Expression Regex

* wap to check characters starting from a ending with b.

In [73]:
# . used to ignore the btw characters.
import re
res = re.findall(r'a.b','abc adb cvb aeb abcdefb')
print(res)

['adb', 'aeb']


In [78]:
"^ checks whether the str contains the starting word as given in function."
import re
res = re.findall(r'^Hello','Hello worldHello hi hiworld Hello World')
print(res)

['Hello']


In [81]:
"$ checks whether the str contains the starting word as given in function."
import re
res = re.findall(r'Hello$','Hello worldHello hi hiworld Hello')
print(res)

['Hello']


In [82]:
'*'
import re
res = re.findall(r'ca*t','cat caaat caat cbt taac,ct')
print(res)

['cat', 'caaat', 'caat', 'ct']


In [1]:
'+'
import re
res = re.findall(r'cat','cat caaat caat cbt taac,ct')
print(res)

['cat']


In [84]:
'?'
import re
res = re.findall(r'ca?t','cat caaat caat cbt taac,ct')
print(res)

['cat', 'ct']


In [86]:
'{n}'
import re
res = re.findall(r'a{1}','cat caaat caat cbt taac,ct')
print(res)

['a', 'a', 'a', 'a', 'a', 'a', 'a', 'a']


In [87]:
'{n,}'
import re
res = re.findall(r'a{2,}','cat caaat caat cbt taac,ct')
print(res)

['aaa', 'aa', 'aa']


In [90]:
'{n,m}'
import re
res = re.findall(r'a{1,3}','cat caaat caat cbt taac,ct')
print(res)

['a', 'aaa', 'aa', 'aa']


In [93]:
'[]'
import re
res = re.findall(r'[caa]','cat caaat caat cbt taac,ct')
print(res)

['c', 'a', 'c', 'a', 'a', 'a', 'c', 'a', 'a', 'c', 'a', 'a', 'c', 'c']


In [96]:
'\d'
import re
res = re.findall(r'\d+','124 cat caaat caat cbt 45 taac,ct')
print(res)

['124', '45']


# Dictionary


In [2]:
#syntax
#dict = {key1:value1,key2:value2:key3:value3......,keyN:valueN}


In [4]:
student = {
    "name":"aman",
    "age":21,
    "course":"AI/ML"
}
# student["address"]="Jabalpur"
student["age"]=16
print(student)
print(student["name"])
print(student.get("name"))
#print(student["address"])
print(student.get("address"))
print(student.get("address","not")) #most Preferable.
print(student.get("name","Not Available")) #most Preferable.

{'name': 'aman', 'age': 16, 'course': 'AI/ML'}
aman
aman
None
not
aman


In [32]:
student.pop("course")

'AI/ML'

In [33]:
print(student)

{'name': 'aman', 'age': 16, 'address': 'Jabalpur'}


In [34]:
del student["age"]
print(student)

{'name': 'aman', 'address': 'Jabalpur'}


In [36]:
student.popitem()
student.clear()
print(student)

{}


In [46]:
dict = {'a':1,'b':2,'a':1,'c':3,'d':4,'e':5,'b':6}
for key in dict:
    print(key)

for value in dict.values():
    print(value)

for key,value in dict.items():
    print(f"{key}:{value}")

a
b
c
d
e
1
6
3
4
5
a:1
b:6
c:3
d:4
e:5


* WAP to count te frequency of word?

In [1]:
word = "Hello Java Hello Python"
word_count ={}

for words in word.split():
    word_count[words] = word_count.get(words,0)+1

print(word_count)

{'Hello': 2, 'Java': 1, 'Python': 1}


In [17]:
str = "a,b,a,c,b,d,a"
dict = {}
for i in str.split(","):
    dict[i] = dict.get(i,0)+1

print(dict)
print(dict['a'])

{'a': 3, 'b': 2, 'c': 1, 'd': 1}
3


* WAP to print the majority element in the list.

In [21]:
lst = [1,2,3,2,2,2,2,1,3,4,1,2,2,2,2,2,2]
n = len(lst)
dict = {}

for i in lst:
    dict[i]=dict.get(i,0)+1
for key,value in dict.items():
    if(value>n//2):
        print(key)
        break

2


* majority 2 = WAP to find the majority element.

In [29]:
lst = [1,2,3,2,2,2,2,2,2,2,2,2,2,1,3,4,1,2,2,2,2,2,2,4,4,4,4,4,4,4,4,4,4,4,4,4,4,44,4,4,4,4]
n = len(lst)
dict = {}
lst1 =[]

for i in lst:
    dict[i] = dict.get(i,0)+1
    
for key,value in dict.items():
    if(value>n//3):
        lst1.append(key)
        

print(lst1)        
        

[2, 4]


* WAP to count the frequency of characters in a given string

In [33]:
word = "remmember"
word_count ={}

for words in word:
    word_count[words] = word_count.get(words,0)+1

print(word_count)

{'r': 2, 'e': 3, 'm': 3, 'b': 1}


# Dictionary Comprehension

In [34]:
dict = {1:1,2:2,3:3,4:4}
for key,value in dict.items():
    dict[key] = value**2

for key,value in dict.items():
    print(f"{key}:{value}")

1:1
2:4
3:9
4:16


In [36]:
dict = {x:x**2 for x in range(1,5)}
print(dict)

{1: 1, 2: 4, 3: 9, 4: 16}


* WAP to swap key and values 

In [43]:
dict = {'a':1,'b':2,'c':3,'d':4}
dict1 ={}
for key,value in dict.items():
     print(f"{value}:{key}")
print(dict)

1:a
2:b
3:c
4:d
{'a': 1, 'b': 2, 'c': 3, 'd': 4}


In [45]:
dict = {'a':1,'b':2,'c':3,'d':4}
dict1 ={}

for key,value in dict.items():
    dict1[value]=key

print(dict1)

{1: 'a', 2: 'b', 3: 'c', 4: 'd'}


* WAP to find common keys into two dictionaries

In [49]:
a = {'a':1,'b':2,'c':3,'d':4,'e':5,'f':6}
b = {'abc':454,'b':343,'cds':342,'d':454,'ewe':523,'fhg':611,'e':21}
lst = []
for keys,value in a.items():
    for i,j in b.items():
        if(keys==i):
         lst.append(keys)
print(lst)

['b', 'd', 'e']


# List Comprehension

In [51]:
n = int(input("Enter the size of list:"))
lst = [int(input("Enter the element:")) for i in range(n)]
print(lst)

Enter the size of list: 4
Enter the element: 12
Enter the element: 32
Enter the element: 22
Enter the element: 1


[12, 32, 22, 1]


In [52]:
row = int(input("Enter the number of rows:"))
col = int(input("Enter the number of columns:"))
lst = [[int(input("Enter the element:")) for i in range(col)]for j in range(row)]
print(lst)

Enter the number of rows: 2
Enter the number of columns: 2
Enter the element: 1
Enter the element: 3
Enter the element: 4
Enter the element: 5


[[1, 3], [4, 5]]


* WAP to create two matrix and find the addition of the matrix.

In [61]:
row1 = int(input("Enter the number of rows1:"))
col1 = int(input("Enter the number of columns1:"))
lst1 = [[int(input("Enter the element:")) for i in range(col1)]for j in range(row1)]
print(lst1)
row2 = int(input("Enter the number of rows2:"))
col2 = int(input("Enter the number of columns2:"))
lst2= [[int(input("Enter the element:")) for i in range(col2)]for j in range(row2)]
print(lst2)
lst = [[lst1[i][j] + lst2[i][j] for j in range(len(lst1[0]))]for i in range(len(lst1))]
print("The sum of two lists are:",lst)


Enter the number of rows1: 2
Enter the number of columns1: 2
Enter the element: 1
Enter the element: 2
Enter the element: 3
Enter the element: 4


[[1, 2], [3, 4]]


Enter the number of rows2: 2
Enter the number of columns2: 2
Enter the element: 6
Enter the element: 6
Enter the element: 5
Enter the element: 6


[[6, 6], [5, 6]]
The sum of two lists are: [[7, 8], [8, 10]]


# Join Function
->To convert the list into the string.

In [72]:
str = "Hi, welcome to the python classes"
lst = str.split()
lst.reverse()
str2= " ".join(lst)
print(lst)
print(str2)

['classes', 'python', 'the', 'to', 'welcome', 'Hi,']
classes python the to welcome Hi,


# *Introduction to Pandas and Numpy*

In [75]:
import numpy as np
import pandas as pd
print(numpy.__version__)
print(pandas.__version__)


1.26.4
2.1.4


In [83]:
import numpy as np
lst = np.array([1,2,3,4,5])
print(lst)

[1 2 3 4 5]


In [84]:
row = int(input("Enter the number of rows:"))
col = int(input("Enter the number of columns:"))
lst = [[int(input("Enter the element:")) for i in range(col)]for j in range(row)]
arr = np.array(lst)
print(arr)

Enter the number of rows: 3
Enter the number of columns: 3
Enter the element: 1
Enter the element: 2
Enter the element: 3
Enter the element: 4
Enter the element: 5
Enter the element: 6
Enter the element: 7
Enter the element: 8
Enter the element: 9


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [91]:
import random 
arr = np.zeros((2,2))
print(arr)
arr2 = np.ones((2,2))
print(arr2)

arr3 = np.random.rand(2,2)
print(arr3)

[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]]
[[0.27918113 0.75124792]
 [0.56296558 0.83629147]]


In [94]:
arr = np.arange(1,16,2)
print(arr)

[ 1  3  5  7  9 11 13 15]


In [96]:
arr = np.linspace(1,2,6) #Takes in 6 equal fragments.
print(arr)

[1.  1.2 1.4 1.6 1.8 2. ]


In [100]:
arr = np.linspace(1,2,3) #Takes in 6 equal fragments.
print(arr)

[1.  1.5 2. ]


In [105]:
arr = np.array([1,2,3,4,5])
print(arr+5)
print(arr*2)

[ 6  7  8  9 10]
[ 2  4  6  8 10]


In [109]:
arr = np.array([1,2,3,4])
arr1 = np.array([6,6,7,8])
print("The sum of two arrays:",arr+arr1)
print("The product of two arrays:",arr*arr1)

The sum of two arrays: [ 7  8 10 12]
The product of two arrays: [ 6 12 21 32]


In [173]:
# row1 = int(input("Enter the number of rows1:"))
col1 = int(input("Enter the number of columns1:"))
lst1 = [[int(input("Enter the element:")) for i in range(col1)]for j in range(row1)]
print(lst1)
row2 = int(input("Enter the number of rows2:"))
col2 = int(input("Enter the number of columns2:"))
lst2= [[int(input("Enter the element:")) for i in range(col2)]for j in range(row2)]
arr = np.array(lst1)
arr1 = np.array(lst2)
print(lst2)
print("The sum of 2 arrays are:",arr+arr1)
print("The sum of 2 arrays are:",arr*arr1)

Enter the number of columns1: 1
Enter the element: 1
Enter the element: 1


[[1], [1]]


Enter the number of rows2: 1
Enter the number of columns2: 1
Enter the element: 1


[[1]]
The sum of 2 arrays are: [[2]
 [2]]
The sum of 2 arrays are: [[1]
 [1]]


In [120]:
arr = np.array([10,100,1000])
print(np.sqrt(arr))
print(np.sin(arr))
print(np.log(arr)) #Base 2(natura log)

[ 3.16227766 10.         31.6227766 ]
[-0.54402111 -0.50636564  0.82687954]
[2.30258509 4.60517019 6.90775528]


In [124]:
arr = np.array([1,2,3,4,5,6,7])
print(np.mean(arr))
print(np.std(arr)) #mean/2. 
print(np.sum(arr))
print(arr[arr>3])

4.0
2.0
28
[4 5 6 7]


* WAP to create a numpy array of numbers from 1-9 and reshape it into a 3X3 matrix

In [125]:
# col1 = int(input("Enter the number of columns1:"))
# lst1 = [[int(input("Enter the element:")) for i in range(col1)]for j in range(row1)]
# print(lst1)
# row2 = int(input("Enter the number of rows2:"))
# col2 = int(input("Enter the number of columns2:"))
# lst2= [[int(input("Enter the element:")) for i in range(col2)]for j in range(row2)]

[1 2 3 4 5 6 7 8 9]


In [128]:
#1st Approach.
# lst = [x for x in range(1,10)]
arr = np.arange(1,10).reshape(3,3)
print(arr)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [129]:
#2nd approach.
lst = [x for x in range(1,10)]
arr = np.array(lst).reshape(3,3)
print(arr)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


* WAP to find the max and min value in an array.
  

In [135]:
lst = [x for x in range(1,10)]
# arr = np.min(lst)
# arr1 = np.max(lst)
print("The minimum element is:",np.min(lst))
print("The maximum array is",np.max(lst))

The minimum element is: 1
The maximum array is 9


* WAP to find the transpose of the matrix and inverse.

In [178]:
arr = np.array([[1,2],[3,4]])
print(np.transpose(arr))
det = np.linalg.det(arr)
print(det)
if(det!=0):
    inv = np.linalg.inv(arr)
    print(inv)
else:
    print("Inverse is not possible")
# print(np.linalg.inv(arr))

[[1 3]
 [2 4]]
-2.0000000000000004
[[-2.   1. ]
 [ 1.5 -0.5]]


* WAP to convert 2X2 matrix into 1d)

In [179]:
arr = np.array([[1,2],[3,4]])
arr1 = np.array(arr).flatten()
print(arr1)

[1 2 3 4]


* Split a 1D array in 3 parts.

In [180]:
arr = [i for i in range(1,12)]
parts = np.array_split(arr,3)
print(parts)
for i,j in enumerate(parts,1):
    print(f"part {i}:",j)

[array([1, 2, 3, 4]), array([5, 6, 7, 8]), array([ 9, 10, 11])]
part 1: [1 2 3 4]
part 2: [5 6 7 8]
part 3: [ 9 10 11]


In [39]:
import pandas as pd
data = pd.Series([1,2,3,4,5,6,7])
print(data)


0    1
1    2
2    3
3    4
4    5
5    6
6    7
dtype: int64


In [40]:
data = pd.DataFrame({
    "Name":["Aman","Prince","Priyanka","Rohit"],
     "Age":[25,24,25,26],
     "Salary" :[30000,50000,25000,40000]
})
print(data)

       Name  Age  Salary
0      Aman   25   30000
1    Prince   24   50000
2  Priyanka   25   25000
3     Rohit   26   40000


In [41]:
data = pd.read_csv(r'C:\Users\DELL\Downloads\Student_details.csv - Sheet1.csv')
print(data)

       Name   Age Branch  SGPA  CGPA      Address
0     Vedant   20  AI/ML  7.77  7.75      Tilheri
1      Jatin   20  AI/ML  7.10  7.20  Madan Mahal
2  Shambhavi   21  AI/ML  7.75  7.45         RDVV
3       Urja   21  AI/ML  7.58  7.68        Ukhri
4       Yash   20    IOT  7.50  7.46   Aaga chowk


In [42]:
print(data.head())

       Name   Age Branch  SGPA  CGPA      Address
0     Vedant   20  AI/ML  7.77  7.75      Tilheri
1      Jatin   20  AI/ML  7.10  7.20  Madan Mahal
2  Shambhavi   21  AI/ML  7.75  7.45         RDVV
3       Urja   21  AI/ML  7.58  7.68        Ukhri
4       Yash   20    IOT  7.50  7.46   Aaga chowk


In [43]:
print(data.tail())

       Name   Age Branch  SGPA  CGPA      Address
0     Vedant   20  AI/ML  7.77  7.75      Tilheri
1      Jatin   20  AI/ML  7.10  7.20  Madan Mahal
2  Shambhavi   21  AI/ML  7.75  7.45         RDVV
3       Urja   21  AI/ML  7.58  7.68        Ukhri
4       Yash   20    IOT  7.50  7.46   Aaga chowk


In [44]:
print(data[data["Age"]>20])

       Name   Age Branch  SGPA  CGPA Address
2  Shambhavi   21  AI/ML  7.75  7.45    RDVV
3       Urja   21  AI/ML  7.58  7.68   Ukhri


In [45]:
data.drop("SGPA",axis=1,inplace=True)
print(data)

       Name   Age Branch  CGPA      Address
0     Vedant   20  AI/ML  7.75      Tilheri
1      Jatin   20  AI/ML  7.20  Madan Mahal
2  Shambhavi   21  AI/ML  7.45         RDVV
3       Urja   21  AI/ML  7.68        Ukhri
4       Yash   20    IOT  7.46   Aaga chowk


In [46]:
print(data.describe())

             Age      CGPA
count   5.000000  5.000000
mean   20.400000  7.508000
std     0.547723  0.217187
min    20.000000  7.200000
25%    20.000000  7.450000
50%    20.000000  7.460000
75%    21.000000  7.680000
max    21.000000  7.750000


In [47]:
print(data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   Name     5 non-null      object 
 1   Age      5 non-null      int64  
 2   Branch   5 non-null      object 
 3   CGPA     5 non-null      float64
 4   Address  5 non-null      object 
dtypes: float64(1), int64(1), object(3)
memory usage: 332.0+ bytes
None


In [48]:
print(data.columns)

Index(['Name ', 'Age', 'Branch', 'CGPA', 'Address'], dtype='object')


In [49]:
x=data.groupby("Age").mean("Age")
print(x)

      CGPA
Age       
20   7.470
21   7.565


In [50]:
# merge = pd.merge(data1,data2,on = 'key_column')
# concat = pd.concat([data1,data2],axis=0)

In [4]:
df = pd.read_csv(r'C:\Users\DELL\Downloads\Book(Sheet1).csv')
print(df)

NameError: name 'pd' is not defined

In [1]:
df.columns

NameError: name 'df' is not defined

In [53]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Name      9 non-null      object 
 1   Age       9 non-null      int64  
 2   Roll no.  9 non-null      int64  
 3   CGPA      9 non-null      float64
 4   Address   9 non-null      object 
 5   Branch    9 non-null      object 
dtypes: float64(1), int64(2), object(3)
memory usage: 564.0+ bytes


In [54]:
df.describe()

Age   Roll no.      CGPA
count   9.000000   9.000000  9.000000
mean   20.555556  51.444444  7.227778
std     0.726483  20.952990  0.383333
min    20.000000  20.000000  6.700000
25%    20.000000  33.000000  6.900000
50%    20.000000  60.000000  7.200000
75%    21.000000  70.000000  7.500000
max    22.000000  72.000000  7.800000

In [55]:
df.head()

Name  Age  Roll no.  CGPA      Address Branch
0     Jatin    20        27  7.20  Madan Mahal   AIML
1  Shambhavi   21        60  7.45         RDVV   AIML
2     Vedant   20        70  7.60      Tilheri   AIML
3       Urja   21        68  7.50        Ukhri   AIML
4       Yash   20        72  7.10   Aaga Chowk    IOT

In [56]:
data[data['Age']>20]

Name   Age Branch  CGPA Address
2  Shambhavi   21  AI/ML  7.45    RDVV
3       Urja   21  AI/ML  7.68   Ukhri

In [58]:
data[data['Branch']!='AI/ML']

Name   Age Branch  CGPA     Address
4  Yash   20    IOT  7.46  Aaga chowk