<a href="https://colab.research.google.com/github/jatinpasi27/Python_basix/blob/main/Python_Introduction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Print Statement.**#

In [ ]:
print("Here we are starting with python.")

print("Hello World!")
print("Python","is","an","interpreted",sep = "~",end = " Language")#sep is used to add a sign to seperate the words.


Here we are starting with python.
Hello World!
Python~is~an~interpreted Language

#**Variables**#

In [ ]:
a = 21 # here a & b are variables which store some type of values in it.
print(a)
b = 2.43
print(b)

21
2.43


#**Data types**#

Data types can be refered to as varibles which store different types of values in it.

In [ ]:
from os import get_blocking
#Typecheck
a = 23
b = 34.54
c = "Machine learning"
d = True
e = 4.5454545454545545454
f = [5,64,3,6,26,2]
g = ("jatin","gaurav","nanu","bhoomi","shanvi","pihu")
h = {23,43,5,6,55,98}
print(type(a))
print(type(b))
print(type(c))
print(type(d))
print(type(e))
print(type(f))
print(type(g))
print(type(h))


<class 'int'>
<class 'float'>
<class 'str'>
<class 'bool'>
<class 'float'>
<class 'list'>
<class 'tuple'>
<class 'set'>


#**Calculator**#

In [ ]:
a = 12
b = 3
print("The addition of a & b are:",a+b)
print("The subtraction of a & b are:",a-b)
print("The multiplication of a & b are:",a*b)
print("The division of a & b are:",a/b)
print("The modulus of a & b are:",a%b)
print("The Floor division of a & b are:",a//b)

The addition of a & b are: 15
The subtraction of a & b are: 9
The multiplication of a & b are: 36
The division of a & b are: 4.0
The modulus of a & b are: 0
The Floor division of a & b are: 4


##**Type Conversion**##

In [ ]:
a = 18
print(a)
print(float(a))


18
18.0


#**Escape Sequence**#

In [ ]:
print("This is google colab") #here we are printing this sentence in one line.

print("This is google \ncolab") #here we are printing similar sentence in two diff lines using escape sequence.

print("This is google \tcolab") #here we are printing similar sentence by providing space using \t seq.

print("This is google \bcolab") #here we are printing similar sentence by del the space btw google and colab using \b sequence.

print("This is google \\colab") #here we are printing similar sentence by del the space btw google and colab using \b sequence.

print("This is google \"colab\"") #here we are printing similar sentence by del the space btw google and colab using \b sequence.


This is google colab
This is google 
colab
This is google 	colab
This is google colab
This is google \colab
This is google "colab"


#**Control Statements**#

#**If else statement(Even odd)**#

In [ ]:
a =24
if(a%2==0):#Intendation should be kept in mind.
  print("a is an Even number.")
else:
  print("a is an Odd number.")

a is an Even number.


**Wap to check whether the number is greater than 50 or not and if greater then check whether it is even or not also check the same for odd number too.**

In [ ]:
# num = 55
# if num > 50 :
#   print("The number is greater than 50.")
# else:
#   print("The number is smaller than 50")
num = 55
if num>50:
   if num %2==0:
    print("The number is greater than 50 and is even.")
   else:
    print("The number is greater but not even.")
else:
   if num %2!=0:
    print("The number is less than 50 and is odd.")
   else:
    print("The number is less than 50 but not odd.")

The number is greater but not even.


In [ ]:
age = 34
if(age>=18):
  print("Candidate is eligible to vote.")
else:
  print("Candidate is not eligible to vote.")

Candidate is eligible to vote.


**Adding elif statement in this.**





In [ ]:
a = 34
b = 34
if(a > b):
  print("A is greater than B.")

elif(b>a):
  print("B is greater than A.") #This is used to create a ladder of if-else statement.

else:
  print("Both are equal to each other.")

Both are equal to each other.


#**Area of a cube**

In [ ]:
side = 25
area = side**2
print("The area of cube is:",area)

The area of cube is: 625


#**Taking input from user**#

In [ ]:
a = input("Enter the number:") #here,its considering input as string by default, to avoid this we have to
print(a) #typecast it by int datatype so as to make it int input.

b = a+'4'#Here,Concatenation is helding to this o/p.
print(b)

Enter the number:34
34
344


##**Project 1**##

In [ ]:
import time
time = time.strftime('%H:%M:%S')
print(time)


14:04:55


In [ ]:
a = int(input("Enter the number:")) #here,its considering input as string by default, to avoid this we have to
print(a) #typecast it by int datatype so as to make it int input.
b = a+4
print(b)

Enter the number:5
5
9


In [ ]:
a = int(input("Enter the num:"))
print(float(a)) #TYPE-CASTING

Enter the num:56
56.0


#**Swapping 2 numbers**#

In [ ]:
num1 = int(input("Enter First number:"))
num2 = int(input("Enter second number:"))
temp = num1
num1 = num2
num2 = temp
print("The value of num1 is :",num1)
print("The value of num2 is :",num2)


Enter First number:43
Enter second number:66
The value of num1 is : 66
The value of num2 is : 43


#**Now, we'll learn about Strings.**#

In [ ]:
n = "Hello"
print(n)
print("hello,"+n) #This is known as Concatenation.Where 2 strings are combined together.


Hello
hello,Hello


In [ ]:
lang = "cpp is an essential language for DSA."
for i in lang:
  print(i)

c
p
p
 
i
s
 
a
n
 
e
s
s
e
n
t
i
a
l
 
l
a
n
g
u
a
g
e
 
f
o
r
 
D
S
A
.


#**Some Operations on strings!**#

In [ ]:
a = "Machine"
b = "learning"
c = "python is an easy language!!!"
d = "Dsa Is The Foundational Subject\n"
e = "pandas is a library"
f = " "

print(len(a))
print(a.islower())#checks whether the string is in lower-case.
print(a.isupper())
print(a.upper()) #converts string into upper case
print(a.lower())

print(c.replace("python","C++")) #used to replace the string by the new one(modification).

print(b.capitalize()) #used to capitalize the first letter of the string.

print(c.split()) #Creates a list of the given string if spaces are available.
print(c.split()[-2]) #Creates a list of the given string if spaces are available.

print(c.count("a")) #counts the freq of the given args in a string.

print(c.rstrip("!")) #removes the character present at the end of string.(post only)

print(c.endswith("!")) #checks whether the sentence or string ends with the same input.

print(c.endswith("is",4,29)) #same function but checks using slicing.

print(c.endswith("!",4,29)) #same function but checks using slicing.

print(c.startswith("python"))#case-sensative (checks the starting string comparing to input value.)

print(c.startswith("C++"))

print(c.find("is"))#calculates the first occurance of the string and returns the index value where it is stored.

print(c.find("easy"))

print(b.isalnum())#checks whether the string is alphanumeric or not.

print(c.isalnum())#c is not alphanumeric as it contains spaces btw it.

print(b.isalpha()) #determines only alphabets(a-z) [Non case-sensative].

print(c.isprintable())#determines whether the string can be printed or not.
#i.e if any specifier would be present it'll be considered as non-printable.

print(d.isprintable())#is non printable due to the presence of specifier in it.

print(f.isspace()) #checks only n only the space, seems useless.

print(e.istitle())#determines whether the first letter of every word is capital or not.

print(d.istitle())# since d has each n every word has first letter capital it is considered to be True.

print(e.title()) #capitalize first letter of each word.

print(a.swapcase())
print(b.swapcase()) #these both is used to swap the case.If upper then its converted into lower nd vice-versa.



7
False
False
MACHINE
machine
C++ is an easy language!!!
Learning
['python', 'is', 'an', 'easy', 'language!!!']
easy
4
python is an easy language
True
False
True
True
False
7
13
True
False
True
True
False
True
False
True
Pandas Is A Library
mACHINE
LEARNING


##**Project 2: Building a Marksheet of 12th class Student.**##

In [ ]:
name = input("Enter the name of the student:")
mat = int(input("Enter the marks in Maths:"))
phy = int(input("Enter the marks in Physics:"))
chem = int(input("Enter the marks in Chemistry:"))
eng = int(input("Enter the marks in English:"))
PE = int(input("Enter the marks in Physical Education:"))
total = mat+phy+chem+eng+PE
percentage = total/5
if(percentage<=100 and percentage>=90):
 print(name, "scored",percentage," Grade and secured 1st Division.")
elif(percentage>=60 and percentage<=89):
   print(name, "scored",percentage," Grade and secured 1st Division.")
elif(percentage>=50 and percentage<=59):
   print(name, "scored",percentage," Grade and secured 2nd Division.")
else:
   print(name, "Failed in examination.")


Enter the name of the student:Chamarkant
Enter the marks in Maths:80
Enter the marks in Physics:67
Enter the marks in Chemistry:98
Enter the marks in English:56
Enter the marks in Physical Education:77
Chamarkant scored 75.6  Grade and secured 1st Division.


#**String Slicing**#

In [ ]:
a = "Artificial"
print(a[0:7])
print("The length of the string is:",len(a))

b = "Intelligence"

print("The length of b is:",len(b))

print(b[0:6])

print(b[5:11])

print(b[0:len(b)-3])

print(b[0:-3]) #same as abv (KNOWN AS NEGATIVE SLICING)

print(b[-4:-2],"\n\n") #11-4 = 7

print(b)
print(b[-4:-5]) #this will not print due to wrogn assignment of slicing

print(b[-4:-3]) #The 2nd no should always be smaller than the firstone.


Artific
The length of the string is: 10
The length of b is: 12
Intell
ligenc
Intellige
Intellige
en 


Intelligence

e


#**Control Statements**#

There are 3 types of control statements
* Looping = These statements allow a program to execute a block of code repeatedly.
->For loop=This comprises of initialization,condition and then termination(increment/decrement).
->While loop=This comprises of the initialization beforehand and then condition termination at the last of loop.
->Do-While loop=This is used to execute the loop at least once.


* Switch Case



#**FOR LOOP.**#

In [ ]:
#FOR LOOP.
a = 5
for i in range(1,a+1):
  print(i)


In [ ]:
#Printing even num.
a = int(input("Enter the number:"))
for i in range(1,a+1):
  if(i%2==0):
    print(i)  #Intendation.


Enter the number:5
2
4


In [ ]:
#For odd numbers:
a = int(input("Enter the num:"))
for i in range(1,a+1):
  if(i%2==1):
   print(i)  #Intendation.


Enter the num:4
1
3


In [ ]:
#Printing numbers by jumping through addition of some specific number using third block of loop.
for i in range(1,20+1):
  print(i)



1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20


#**Table of any number.**#

In [ ]:
#printing table of any number.
n = int(input("Enter the number:"))
for i in range(1,11):
  print(n,"x",i,"=",n*i)

Enter the number:5
5 x 1 = 5
5 x 2 = 10
5 x 3 = 15
5 x 4 = 20
5 x 5 = 25
5 x 6 = 30
5 x 7 = 35
5 x 8 = 40
5 x 9 = 45
5 x 10 = 50


#**WAP to swap two numbers if the first number is greater than the second number.**#

In [ ]:
a = int (input ('Enter 1st number:'))
b = int (input ('Enter 1st number:'))
if(a>b):
  temp = a
  a = b
  b = temp
  print("The value of a is:",a)
  print("The value of b is:",b)

else:
  print("The value of a is:",a)
  print("The value of b is:",b)

Enter 1st number:98
Enter 1st number:78
The value of a is: 78
The value of b is: 98


#**Same values will have same memory location**#

In [ ]:
a = 2
b = 4
c = 343
d = 343
print(c==d)
print(a is not b)  #Need to ask about it later onn...
print(c is not d)
print(c is  d)

True
True
True
False


In [ ]:
a = 34
b = 33+1
print(a==b)
print(a is b)
print(hex(id(a)))  #Used for knowing memory location.
print(hex(id(b)))  #hexadecimal address

True
True
0x7d2b85060510
0x7d2b85060510


# Loop in strings

In [ ]:
a = "Python"
for i in a:
  print(i)
  if(i=='t'):
    continue



#**Prime number**#

In [ ]:
a = int(input("Enter the number:"))
for i in range(2,a):
  if(a%i==0):
    print("Not a Prime number")
    break
else:
  print("Prime Number")

Enter the number:4
Not a Prime number


#**Factorial**#

In [ ]:
a = int(input("Enter the number:"))
fact = 1
for i in range(1,a+1):
  fact = fact*i
print("The factorial of",a,"is",fact)

Enter the number:5
The factorial of 5 is 120


**While Factorial**

In [ ]:
n = int(input("Enter the number:"))
fact = 1
i = 1
while(i<=n):
  fact = fact*i
  i=i+1
print("The value of factorial",n,"is",fact)


Enter the number:5
The value of factorial 5 is 120


#**Sum of Natural numbers.**#

In [ ]:
from re import I
n= int(input("Enter the number till where you want the sum of natural no's:"))
sum = 0
for i in range(1,n+1):
  sum = sum+i
print("The sum of",n,"natural numbers are:",sum)


Enter the number till where you want the sum of natural no's:10
The sum of 10 natural numbers are: 55


#**Multiplying 2 no's nd decrementing them untill 0 arises.**#

In [ ]:
a = int(input("Enter the number:"))
b = int(input("Enter the number:"))
for i in range(a,1,-1):
  c = a*b
  print(a,'x',b,'=',c)
  a = a-1
  b = b-1

Enter the number:10
Enter the number:9
10 x 9 = 90
9 x 8 = 72
8 x 7 = 56
7 x 6 = 42
6 x 5 = 30
5 x 4 = 20
4 x 3 = 12
3 x 2 = 6
2 x 1 = 2


In [ ]:
i= 1
while True:
  print(i)
  i +=1
  if(i%50==0):
    break

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49


In [ ]:
a = int(input("Enter the number:"))
b = int(input("Enter the number:"))
while(a and b>0):
  c = a*b
  print(a,'x',b,'=',c)
  a = a-1
  b = b-1

Enter the number:6
Enter the number:4
6 x 4 = 24
5 x 3 = 15
4 x 2 = 8
3 x 1 = 3


#**Prime number using while loop**#

In [ ]:
a = int(input("Enter the number:"))
i=2
while(i!=a):
  if(a%i==0):
    print("Not a prime number..")
    break
  else:
    print("Is a prime number.")
    break


Enter the number:4
Not a prime number..


#**Sum of natural numbers using while loop**#

In [ ]:
a = int(input("Enter the number:"))
i = 0
sum = 0
while(i!=a+1):
  sum = sum+i
  i += 1
print("The sum of",a,"natural no.s are",sum)

#**Factorial using while loop**#

In [ ]:
a = int(input("Enter the number:"))
fact = 1
i = 1
while(i<=a):
  fact = fact*i
  i+=1
print("The factorial of",a,"is",fact)

#**WAP to check which number is greater**#

In [ ]:
a = int(input("Enter the number a:"))
b = int(input("Enter the number b:"))
c = int(input("Enter the number c:"))

if(a > (b and c)):
  print("a is greatest number of all")
elif(b > (a and c)):
  print("b is greatest number of all")
else:
  print("c is greatest number of all")


##**Functions in Python**##

**using libraries**

In [ ]:
import pandas as pd
import numpy as np
a = [1,2,3,4,5,6,7,8,9,10]
print(type(a))
print(np.max(a))
print(np.sum(a))
print(np.min(a))

<class 'list'>
10
55
1


In [ ]:
def square(a):
  sq = a*a
  return sq
b = square(2)
print(b)

4


In [ ]:
def add(a,b): #function prototype!
  c = a + b
  print(c)     #function defination!

add(5,3)   #function call.


In [ ]:
def islesser(a,b):
  if(a<b):
    print(a,"a is lesser.")
  else:
    print(b,"b is lesser.")
islesser(4,45)


4 a is lesser.


In [ ]:
def isgreater(j,k):
  pass

def isgreater(j,k):
  if(j>k):
   print(j,"j is greater.")
  else:
   print(k,"k is greater.")
isgreater(45654,4343)

45654 j is greater.


In [ ]:
def avg(a,b):   #Here, we are taking only 2 args.
  print("The avg is:",(a+b)/2)
avg(49,3)

def average(a =2 , b =4 ):    #These are required args.
  print("The avg is:",(a+b)/2)
average(5,10)   #ALSO CALLED DEFAULT ARGS.
#The output here is of 15 as the modified value is considered.


The avg is: 26.0
The avg is: 7.5


In [ ]:
def avg(*num):#Here we can take multiple args nd accordingly it will ans the correct average of the given nums.
  sum = 0
  for i in num:
    sum = sum + i
    print("The avg is:",sum/len(num))
avg(4,3,12,1)


The avg is: 1.0
The avg is: 1.75
The avg is: 4.75
The avg is: 5.0


In [ ]:
#Keyword args
def name(fname,mname,lname):
 print(type(name))
 print("HELLO!",fname,mname,lname)
name(mname = "shivaji", lname = "Maharaj",fname="Chattrapati")

<class 'function'>
HELLO! Chattrapati shivaji Maharaj


In [ ]:
def name(*name):
  print(type(name))
  print("Hello!",name[0],name[1],name[2])
name("Subhash","Chandra","Bose")

<class 'tuple'>
Hello! Subhash Chandra Bose


Keyword arbitrary arguments.

In [ ]:
def name(**name):
  print(type(name))
  print("Hello!",name["fname"],name["mname"],name["lname"])
name(mname = "Abdul",fname = "APJ",lname = "Kalam")

<class 'dict'>
Hello! APJ Abdul Kalam


In [ ]:
i = 0
while True:
  print(i)
  i = i+1
  if(i%50==0):
    break
  if(i==45):
    continue

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49


#**Questions**#

In [ ]:
def fun(n,l=[]):
  for i in range(n):
    l.append(i*i)
  print(l)
fun(2)

[0, 1]


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
i =1
while True:
  if i%9==0:
    break
  print(i+4)
  i +=2

5
7
9
11


In [ ]:
a = 'internshala'
print(len(a))
for i in range(len(a)):
  print(a)
  # a = 'z'

11
internshala
internshala
internshala
internshala
internshala
internshala
internshala
internshala
internshala
internshala
internshala


#**Wap to check whether the number is greater than 50 or not and if greater then check whether it is even or not also check the same for odd number too.**#

In [ ]:
# num = 55
# if num > 50 :
#   print("The number is greater than 50.")
# else:
#   print("The number is smaller than 50")
num = 55
if num>50:
   if num %2==0:
    print("The number is greater than 50 and is even.")
   else:
    print("The number is greater but not even.")
else:
   if num %2!=0:
    print("The number is less than 50 and is odd.")
   else:
    print("The number is less than 50 but not odd.")

The number is greater but not even.


In [ ]:
def fun(x,y):
  if x>y:
    return x
  elif x==y:
    return x,y
  else:
    return y
print(fun(20,30))

30


#**Finding out number of combination using simple method and then using functions**#

In [ ]:
n =10
r =6

fact_n =1
for i in range(1,n+1):
  fact_n = fact_n*i

fact_r =1
for i in range(1,r+1):
  fact_r = fact_r*i

fact_n_r =1
for i in range(1,(n-r)+1):
  fact_n_r = fact_n_r*i

result = fact_n/(fact_r * (fact_n_r))
print("Number of combination:",result)


Number of combination: 210.0


*Using function*

In [ ]:
#NOW USING FUNCTION
def factorial(para):
  fact = 1
  for i in range(1,para + 1):
    fact = fact * i
  return fact #Intendation should be followed to get the desired output.
n = 10
r = 6
result = factorial(n)/(factorial(r)*(factorial(n-r)))
print("Number of combination",result)

Number of combination 210.0


#**List in Python**#

In [ ]:
l = [2,3,4,45,34,'college','school','industry',34]

print(l) #1st method of printing list.

print(l[:]) #consider index 0 on the left side of the colon. And prints the whole list.

print(l[0:9]) #slicing.

print(len(l)) #Finds out the size of list.

print(type(l))
#SINCE LISTS ARE MUTABLE IN NATURE WHICH MEANS WE CAN MODIFY IT.

l.append(23) #Modification.
print(l)

[2, 3, 4, 45, 34, 'college', 'school', 'industry', 34]
[2, 3, 4, 45, 34, 'college', 'school', 'industry', 34]
[2, 3, 4, 45, 34, 'college', 'school', 'industry', 34]
9
<class 'list'>
[2, 3, 4, 45, 34, 'college', 'school', 'industry', 34, 23]


*Negative Indexing.*

In [ ]:
print(l[:])
print(len(l))
print(l[0:-3])
print(l[1:-3])
print(l[-6:-3]) #Negative Indexing.

print(l[len(l)-6:len(l)-3]) #Easier representation.

print(l[4:7])  #Conversion into Positive Indexing.

[2, 3, 4, 45, 34, 'college', 'school', 'industry', 34, 23]
10
[2, 3, 4, 45, 34, 'college', 'school']
[3, 4, 45, 34, 'college', 'school']
[34, 'college', 'school']
[34, 'college', 'school']
[34, 'college', 'school']


*CHECKING ELEMENTS IN A LIST.*

In [ ]:
#CONSIDERING THE SAME LIST GIVEN AVB.
if 3 in l:      #This is how we can easily check whether the element is present in the list or  not.
  print("Yes")
else:
  print("No")


if 7 in l:
  print('Yes')
else:
  print('No')

if 'school' in l:  #Same appraoch is used in string element as well.
  print('Yes')
else:
  print('No')

if 'chool' in 'school':
  print('yes')
else:
  print('No')

if 'chol' in 'school':
  print('yes')
else:
  print('No')

Yes
No
Yes
yes
No


**JumpIndexing in list**

In [ ]:
list = [23,54,'DataScience','MachineLearning',34,56,77,88,44,98]
print(list)
print(len(list))
print(list[0:9:2])
print(list[0:10:5]) #Using the 3rd block of slicing brackets we can jumpover the certain numbers through which we wish to.

[23, 54, 'DataScience', 'MachineLearning', 34, 56, 77, 88, 44, 98]
10
[23, 'DataScience', 34, 77, 44]
[23, 56]


#**List Comprehension**#

In [ ]:
#LIST COMPREHENSION
lst = [i for i in range(4)]
print(lst)

list = [i*i for i in range(10)] #Here the seq is till 10 excluding 10. and the squares of the numbers are printed.
print(list[1:])

list1 = [i*i for i in range(10) if i%2==0 ]
print(list1)
print(list1[1:]) #list slicing is used to initiate from the 1st index.


[0, 1, 2, 3]
[1, 4, 9, 16, 25, 36, 49, 64, 81]
[0, 4, 16, 36, 64]
[4, 16, 36, 64]


**List Manipulation Methods**

In [ ]:
a = [1,332,443,34,23,1,8]
print(len(a))
print(a)

a.append(65)  #Adds an element in the list.

print(a)

a.sort()  #Used to sort the elements in a list.

print(a)

a.sort(reverse= True ) #Sort the list in descending order.

print(a)

a.reverse()  #reverses the elements of the list

print(a)

#As the operations are held in a list the updation takes place on each operation.


print(a.index(332)) #Tells about the index no of the particular value.

print(a.index(8))

print(a.count(1)) #calculates the freq of the element in a list.
#SUPPOSE A NEW LIST.

# m = a
# m[0] = 0  #This changes the element of list a too.
# print(a)

m = a.copy() #generated a copy of the list.

print(m)

a.insert(5,566) #inserts 566 to the 5th index and shifts the other towards right side.

print(a)

list1 = [400,5000,6500]

a.extend(list1)  #This adds the elements of new list in the earlier list.

print(a)


7
[1, 332, 443, 34, 23, 1, 8]
[1, 332, 443, 34, 23, 1, 8, 65]
[1, 1, 8, 23, 34, 65, 332, 443]
[443, 332, 65, 34, 23, 8, 1, 1]
[1, 1, 8, 23, 34, 65, 332, 443]
6
2
2
[1, 1, 8, 23, 34, 65, 332, 443]
[1, 1, 8, 23, 34, 566, 65, 332, 443]
[1, 1, 8, 23, 34, 566, 65, 332, 443, 400, 5000, 6500]


**List Concatenation**

In [ ]:
m = a + list1
print(m)
#THIS IS HOW LIST CONCATENATION IS DONE.

[1, 1, 8, 23, 34, 566, 65, 332, 443, 400, 5000, 6500, 400, 5000, 6500]


#**Tuples**#
**Tuples are similar to list.The only difference is that tuples are non-mutable.**

In [ ]:
t = (1,2,43,54,655,66,'orange','mango')
tup = (2)
print(type(tup))
print(type(t))
print(t)
print(len(t))

#Slicing in tuple
print(t[:])
print(t[0:5])

print(t[len(t)-3:len(t)-1])
print(t[-3:-1])

#Checking
if 655 in t:
  print("yes")
else:
  print("no")

if 55 in t:
  print("yes")
else:
  print("no")

<class 'int'>
<class 'tuple'>
(1, 2, 43, 54, 655, 66, 'orange', 'mango')
8
(1, 2, 43, 54, 655, 66, 'orange', 'mango')
(1, 2, 43, 54, 655)
(66, 'orange')
(66, 'orange')
yes
no


**Methods in tuple**

->Tuple are immutable in nature.So, if we want to modify them there is only one way (i.e indirect) to do so and that is copying the elements of tuple in the list and then modify it.

In [ ]:
fruits = ('Mango','Banana','Litchi','Guava')
temp = list(fruits)
#Since, the tuple is converted into list.Hence, all the operations of the list can be performed here.
print(temp)
temp.append(34)
temp.append('Grapes')
print(temp)
temp.pop(3) #The element in index number 3 is removed from the list.
print(temp)
temp[2] = 'Dolphin'
print(temp)


['Mango', 'Banana', 'Litchi', 'Guava']
['Mango', 'Banana', 'Litchi', 'Guava', 34, 'Grapes']
['Mango', 'Banana', 'Litchi', 34, 'Grapes']
['Mango', 'Banana', 'Dolphin', 34, 'Grapes']


**Sorting list using loops**

###### Today we will start learing python and further we'll look into data analytics.

In [ ]:
print("Hello World!")

In [ ]:
#This is how we can easily write any equation in jupyter notebook $a = b + c$

In [ ]:
$a=b+c$

In [ ]:
print("Lets start Python")

Lets start Python


# Variables
A Variable can be understood as a container which can store different kind of data such as integer number,decimal number or string.
Conventions:-

1. Cannot start with any special character or numeric value except underscore.
2. Always should be bit descriptive so as to be used as indication for what kind of data is stored in it.
3. Ex-- a,b,c shouldn't be used to store any kind of data during project building.
4. Camel Notation-> This is the best way of naming a variable. This means the first letter of the second word should be Capital.
ex-> MinValue

In [ ]:
a =4


In [ ]:
%whos

Variable   Type    Data/Info
----------------------------
a          int     4


In [ ]:
x = 45
y = 77
x = 3


In [ ]:
%whos

Variable   Type    Data/Info
----------------------------
a          int     4
x          int     3
y          int     77


In [ ]:
a,b,c,d,e = 23,43,55,7.9,44


In [ ]:
%whos

Variable   Type     Data/Info
-----------------------------
b          int      43
c          int      55
d          float    7.9
e          int      44
x          int      3
y          int      77


In [ ]:
del c
del d

In [ ]:
%whos

Variable   Type    Data/Info
----------------------------
b          int     43
e          int     44
x          int     3
y          int     77


In [ ]:
#print d will throw an error as the variable c and d has been deleted above

In [ ]:
com = 5 + 8j
print(type(com))

<class 'complex'>


In [ ]:
%whos

Variable   Type       Data/Info
-------------------------------
b          int        43
com        complex    (5+8j)
e          int        44
x          int        3
y          int        77


# string variable

In [ ]:
s  = "Hello World"
print(s)
print(type(s))

Hello World
<class 'str'>


In [ ]:
%whos

Variable   Type       Data/Info
-------------------------------
b          int        43
com        complex    (5+8j)
e          int        44
s          str        Hello World
x          int        3
y          int        77


# Variable and Operators

In [ ]:
a = 5
b = 20
print("The addition of",a,"and",b,"is",(a+b))
print("The subtraction of",a,"and",b,"is",(a-b))
print("The multiplication of",a,"and",b,"is",(a*b))
print("The division of",a,"and",b,"is",(a/b))
print("The Floor Division of",a,"and",b,"is",(a//b))
print("The Modulus of",a,"and",b,"is",(a%b))
print("The Power of",a,"and",b,"is",(a**b))

The addition of 5 and 20 is 25
The subtraction of 5 and 20 is -15
The multiplication of 5 and 20 is 100
The division of 5 and 20 is 0.25
The Floor Division of 5 and 20 is 0
The Modulus of 5 and 20 is 5
The Power of 5 and 20 is 95367431640625


In [ ]:
%whos

Variable   Type       Data/Info
-------------------------------
a          int        5
b          int        20
com        complex    (5+8j)
e          int        44
s          str        Hello World
x          int        3
y          int        77


In [ ]:
n1 = 34
n2 = 45.76
print(n1+n2)
print(type(n1+n2))

79.75999999999999
<class 'float'>


In [ ]:
v = ((n1+n2)**3)//4
print(v)

126851.0


In [ ]:
s1 = "Hello"
s2 = " World"
sum = s1+s2
print(sum)

Hello World


In [ ]:
10//3 #Floor Division

3

In [ ]:
10/3

3.3333333333333335

In [ ]:
_e = 76.4
print(_e)

76.4


In [ ]:
minValue = 27

In [ ]:
%whos

Variable   Type    Data/Info
----------------------------
minValue   int     27
s1         str     Hello
s2         str      World
sum        str     Hello World


# Type bool and Comparision of the variables

In [ ]:
a = True
b = True
c = False


In [ ]:
%whos

Variable   Type    Data/Info
----------------------------
a          bool    True
b          bool    True
c          bool    False


In [ ]:
print(a and b)

True


In [ ]:
print(a and c)
print(c and a)

False
False


In [ ]:
d = (a or b)
print(d)
print(a or c)
print(c or a)
print(a and d)
print(c and d)

True
True
True
True
False


Bool which consist not as prefix(not opposes the bool)

In [ ]:
not(a)

False

In [ ]:
not(b)

False

In [ ]:
not(c)

True

In [ ]:
t = not(d)
print(t)
print(type(d))

False
<class 'bool'>


In [ ]:
not(a and b) or (c or d)

True

Combine the boolean data


# Comparisions

In [ ]:
print(2<3)


True


In [ ]:
c = 2<3
print(type(c))
print(c)

<class 'bool'>
True


In [ ]:
d = 3 ==4
print(d)
print(type(d))

False
<class 'bool'>


In [ ]:
x = 4
y = 9
z = 8.7
r =-3

In [ ]:
(x<y) and (z<y) or (r == x)


True

In [ ]:
False and False or True

True

In [ ]:
(True or False) and False

False

In [ ]:
print((not(2!=3) and True) or (False and True))

False


# Important Functions
Its a built in function from the language that is supplied to the users to achieve particular task.

Round Function--> Used to round the input value to a specified number of places or to the nearest integer.

In [ ]:
round(45.64)

46

In [ ]:
round(45.4)

45

In [ ]:
round(45.5)

46

In [ ]:
round(4.546,2) #This makes the second place after decimal number.

4.55

In [ ]:
round(6.8)

7

Divmod Function-->This function outputs the quotient and the remainder in a tuple().

In [ ]:
divmod(27,4)

(6, 3)

In [ ]:
divmod(22,11)

(2, 0)

In [ ]:
divmod(87,5)

(17, 2)

In [ ]:
a = divmod(23,5)
print(type(a))
print(a)

<class 'tuple'>
(4, 3)


In [ ]:
print(a[0])
print(a[1])

4
3


In [ ]:
%whos

Variable   Type     Data/Info
-----------------------------
a          tuple    n=2


IsInstance function--> Returns true, if the first arguement of the class. Multiple classes can also be checked at once.

In [ ]:
isinstance(2,int)

True

In [ ]:
isinstance(23.4,float)

True

In [ ]:
isinstance(23+8j,(int,float ,str))
#Since we didnt check complex number in this particular tuple.Therefore the result is false

False

In [ ]:
isinstance(23+8j,(int,float ,str,complex))

True

Power Function

Here the third arguement calculates the modulus with the result of first two arguements.

In [ ]:
pow(2,3)

8

In [ ]:
pow(2,4)

16

In [ ]:
2**4

16

In [ ]:
pow(2,4,7)

2

In [ ]:
pow(5,3,5)

0

Input Function

In [ ]:
a = input("Enter the number:")
print(a)
print(type(a))
#Here the variable a stores 45 as string.

Enter the number: 45


45
<class 'str'>


In [ ]:
num = int(input("Enter the number:"))
print(num)
print(type(num))

Enter the number: 45454


45454
<class 'int'>


# Here are some ways by which you can easily know about any function in python.


In [ ]:
help(pow)

Help on built-in function pow in module builtins:

pow(base, exp, mod=None)
    Equivalent to base**exp with 2 arguments or base**exp % mod with 3 arguments
    
    Some types, such as ints, are able to use a more efficient algorithm when
    invoked using the three argument form.



In [ ]:
pow??

Signature: pow(base, exp, mod=None)
Docstring:
Equivalent to base**exp with 2 arguments or base**exp % mod with 3 arguments

Some types, such as ints, are able to use a more efficient algorithm when
invoked using the three argument form.
Type:      builtin_function_or_method

In [ ]:
help(isinstance)

Help on built-in function isinstance in module builtins:

isinstance(obj, class_or_tuple, /)
    Return whether an object is an instance of a class or of a subclass thereof.
    
    A tuple, as in ``isinstance(x, (A, B, ...))``, may be given as the target to
    check against. This is equivalent to ``isinstance(x, A) or isinstance(x, B)
    or ...`` etc.



# Control Flow in Python

In [ ]:
a = int(input("Enter the number 1:"))
b = int(input("Enter the number 2:"))
if(a>b):
    print(a)
if(b>a):
    print(b)

Enter the number 1: 45
Enter the number 2: 33


45


In [ ]:
a = int(input("Enter the number 1:"))
b = int(input("Enter the number 2:"))
if(a>b):
    # print(a)
    print("a is greater than b")
else:
    print("b is greater than a")

Enter the number 1: 88
Enter the number 2: 090


b is greater than a


In [ ]:
a = float(input("Enter the 1st number:"))
a = float(input("Enter the 2nd number:"))
if b>a:
    print("b is greater than a.")
elif a==b:
    print("Both a and b are equal.")
else:
    print("a is greater than b")

Enter the 1st number: 48
Enter the 2nd number: 55


b is greater than a.


Example:


In [ ]:
a = int(input("Enter the marks:"))
if a>=85:
    print("A Grade")
elif (a < 85) and (a >= 80):
    print("A- Grade")
elif (a<80 ) and (a>=75):
    print("B Grade")
elif a<75 and a >= 70:
    print("B- Grade")
else:
    print("Below Average")

Enter the marks: 90


A Grade


Implementation of else part using elif keyword.

In [ ]:
a = 3
if a > 10:
    print(">10")
elif not(a>10):
    print("Else Part")

Else Part


Nested If

In [ ]:
a = int(input("Enter the number:"))
if a>10:
    print("The number is greater than 10")
    if a<15:
        print("The number is greater than 10 but smaller than 15")
    else:
        print("The number is greater than 10 and 15 both")

Enter the number: 45


The number is greater than 10
The number is greater than 10 and 15 both


# Very important code to understand nested if and else conditions.

In [ ]:
a = int(input("Enter the number:"))
if a>10:
    print(">10")
    print("Inside the top if.")
    if a>20:
        print(">20")
        print("Inside the nested if.")
        if a>30:
            print("inside the nested if of nested if.")
        else:
            print("<=30")
            print("Inside the else part of nested if of nested if.")
    else:
        print("<=20")
        print("Inside the else part of nested if.")

print("Outside all ifs")


Enter the number: 30


>10
Inside the top if.
>20
Inside the nested if.
<=30
Inside the else part of nested if of nested if.
Outside all ifs


Comments

In [ ]:
#single line comment
"""
 User will enter a floating point number lets say 238.95.Your task
is to find out the integer portion before the point
(in this case 238) and then check if that integer portion is an even number or not?

"""
x = float(input("Enter a real number:"))
y = round(x) # helps??
if y>x:
    intPortion = y-1 # 29.6

else:
     intPortion = y
print(intPortion)

Enter a real number: 45.655


45


In [ ]:
#This is second approach of the above code.
x = float(input("Enter a real number:"))
# y = round(x) # helps??
if x>0:
    print(int(x))

else:
    print(x)
# print(intPortion)

Enter a real number: 35.6


35


# Small project which is build using input func if-elif and else condition

In [ ]:
mat = int(input("Enter the marks of maths:"))
chem = int(input("Enter the marks of chemistry:"))
phy = int(input("Enter the marks of physics:"))
eng = int(input("Enter the marks of english:"))
PE = int(input("Enter the marks of Physical Education:"))
totalMarks = mat+eng+phy+chem+PE
percentage = (totalMarks)/500*100
print("The Percentage of the candidate is:",percentage)
if (percentage<50):
    print("Student passed aquiring C Grade.")
elif(percentage > 50 and percentage <= 60):
    print("Student passed aquiring C+ Grade.")
elif(percentage > 60 and percentage <= 70):
    print("Student passed aquiring B Grade.")
elif(percentage > 70 and percentage <= 80):
    print("Student passed aquiring B+ Grade.")
elif(percentage > 80 and percentage <= 90):
    print("Student passed aquiring A Grade.")
elif(percentage > 90 and percentage <= 100):
    print("Student passed aquiring A+ Grade.")
else:
    print("Student failed in the examination.")
print("\n")
print("DONE")

Enter the marks of maths: 78
Enter the marks of chemistry: 76
Enter the marks of physics: 88
Enter the marks of english: 99
Enter the marks of Physical Education: 98


The Percentage of the candidate is: 87.8
Student passed aquiring A Grade.


DONE


# Loops

While Loop.

In [ ]:
n = int(input("Enter the number:"))
i = 1
while(i<n):
    print(i)
    # i = i+1
    i += 1

print("Done")

Enter the number: 5


1
2
3
4
Done


* Printing Even numbers

In [ ]:
n = int(input("Enter the number:"))
i = 1
while(i<=n):
    if(i%2==0):
        print(i)
    i += 1
print("Done")

Enter the number: 50


2
4
6
8
10
12
14
16
18
20
22
24
26
28
30
32
34
36
38
40
42
44
46
48
50
Done


* Printing the odd numbers

In [ ]:
n = int(input("Enter the number:"))
i = 1
while(i<=n):
    if(i%2==1):
        print(i)
    i += 1
print("Done")

Enter the number: 45


1
3
5
7
9
11
13
15
17
19
21
23
25
27
29
31
33
35
37
39
41
43
45
Done


* Printing numbers which are divisible by 3 and 5 both.

In [ ]:
a =  int(input("Enter the number:"))
i  = 1
while(i<=a):
    if(i%3==0 and i%5==0):
        print(f"The number",i,"is divisible by both 3 and 5")
    i += 1
print("Done")

Enter the number: 5


Done


* Print Tables

In [ ]:
a = int(input("Enter the number whose table is to be printed:"))
i = 1
while(i<=10):
    print(a,"X",i,"=",a*i)
    i += 1
print("Done")

Enter the number whose table is to be printed: 5


5 X 1 = 5
5 X 2 = 10
5 X 3 = 15
5 X 4 = 20
5 X 5 = 25
5 X 6 = 30
5 X 7 = 35
5 X 8 = 40
5 X 9 = 45
5 X 10 = 50
Done


* Printing the sum of the product of full table.

In [ ]:
a = int(input("Enter the number whose table's sum is to be printed:"))
i = 1
sum = 0
while(i<=10):
    pro = a*i
    sum = sum + pro
    i += 1
print(sum)

Enter the number whose table's sum is to be printed: 5


275


In [ ]:
a = int(input("Enter the number from where you have to start the range:"))
b = int(input("Enter the number from where you have to end the range:"))
i = a
while(i<=b):
    print(i)
    i+=1
print("DONE")

Enter the number from where you have to start the range: 20
Enter the number from where you have to end the range: 33


20
21
22
23
24
25
26
27
28
29
30
31
32
33
DONE


In [ ]:
#PRINTING EVEN NUMBERS WHICH LIE BTW THE DEFINITE RANGE.
a = int(input("Enter the number from where you have to start the range:"))
b = int(input("Enter the number from where you have to end the range:"))
i = a
while(i<=b):
    if i%2==0:
     print(i)
    i+=1
print("DONE")

Enter the number from where you have to start the range: 2
Enter the number from where you have to end the range: 20


2
4
6
8
10
12
14
16
18
20
DONE


Printing Factorial of a given number using while loop.

In [ ]:
n = int(input("Enter the number:"))
i = 1
fact = 1
while(i<=n):
    fact = fact * i
    i +=1
print(f"The factorial of the given {n} is:{fact}")
print("DONE")

Enter the number: 6


The factorial of the given 6 is:720
DONE


# For Loop


In [ ]:
n = int(input("Enter the number:"))
for i in range(1,n+1):
    print(i)
print("DONE")

Enter the number: 5


1
2
3
4
5
DONE


In [ ]:
n = int(input("Enter the number:"))
for i in range(1,n+1):
    #printing even number
    if(i%2==0):
        print(i)
print("DONE")

Enter the number: 5


2
4
DONE


Printing tables using for loop


In [ ]:
n = int(input("Enter the number whose table is to be printed:"))
for i in range(1,11):
    pro = i*n
    print(f"{n}X{i}={pro}")
print("DONE")

Enter the number whose table is to be printed: 6


6X1=6
6X2=12
6X3=18
6X4=24
6X5=30
6X6=36
6X7=42
6X8=48
6X9=54
6X10=60
DONE


Printing products which are Even in nature.

In [ ]:
n = int(input("Enter the number whose table is to be printed:"))
for i in range(1,11):
    pro = i*n
    if(pro%2==0):
     print(f"{n}X{i}={pro}")
print("DONE")

Enter the number whose table is to be printed: 5


5X2=10
5X4=20
5X6=30
5X8=40
5X10=50
DONE


Printing Factorial of any number.

In [ ]:
n = int(input("Enter the number whose factorial is to be found:"))
fact = 1
for i in range(1,n+1):
    fact = fact*i
print(f"The factorial of given number is {fact}")
print("DONE")

Enter the number whose factorial is to be found: 5


The factorial of given number is 120
DONE


# Printing numbers using loop in reverse order.

In [ ]:
n = int(input("Enter the number:"))
i = n
while(i>0):
    print(f"The number is:{i}")
    i-=1
print("DONE")

Enter the number: 9


The number is:9
The number is:8
The number is:7
The number is:6
The number is:5
The number is:4
The number is:3
The number is:2
The number is:1
DONE


Printing even number is reverse order.

In [ ]:
n = int(input("Enter the number:"))
i = n
while(i>0):
    if(i%2==0):
     print(f"The number is:{i}")
    i-=1
print("DONE")

Enter the number: 9


The number is:8
The number is:6
The number is:4
The number is:2
DONE


Printing odd numbers in reverse order.

In [ ]:
n = int(input("Enter the number:"))
i = n
while(i>0):
    if(i%2==1):
     print(f"The number is:{i}")
    i-=1
print("DONE")

Enter the number: 8


The number is:7
The number is:5
The number is:3
The number is:1
DONE


# Break and Continue Statement

n = int(input("Enter the number:"))
i = 1
while(i<n):
    if i%2==0:
        print(i)
    else:
        pass  #THIS MEANS TO DO NOTHING OR SKIP IF THE ELSE STATEMENT TRIGGERS.
    i += 1
print("DONE")

In [ ]:
n = int(input("Enter the number:"))
i =1
while True:
    # print(i)
    if i % 9 == 0:
       print("inside if")
       break
    else:
        print("inside else")
        i = i+1
print("DONE")

Enter the number: 6


inside else
inside else
inside else
inside else
inside else
inside else
inside else
inside else
inside if
DONE


In [ ]:
n = 10
i = 1
while(True):
    if i%9 != 0:
        print("Inside if")
        i += 1
        continue
    print("Something")
    print("SomethingElse")
    break
print("DONE")

Inside if
Inside if
Inside if
Inside if
Inside if
Inside if
Inside if
Inside if
Something
SomethingElse
DONE


Control Flow For Loop

In [ ]:
l = []
for i in range(0,10,2):
    print(i)
    l.append(i**2)
print(l)

0
2
4
6
8
[0, 4, 16, 36, 64]


Else in For Loop.

In [ ]:
s = {"orange",5.6,"mango"}
x = 1
for i in s:
    print(i)
    x+=1
    if x == 3:
        break
    else:
        pass
else:
    print("Loop conpletes its iterations")

print("OUtside the loop")
print(x)
print(type(s))

orange
5.6
OUtside the loop
3
<class 'set'>


In [ ]:
d = {"mango":44,"orange":-19,"c":"abc"}
for x in d:
    print(x,d[x])
print(d["mango"])

mango 44
orange -19
c abc
44


* Given a list of numbers i.e [1,2,4,-5,7,9,3,2] ,make another list that contains all the items in sorted order from min to max. i.e your result will be another list like [-5,1,2,2,3,3,7,9]

In [ ]:
lst =  [1,2,4,-5,7,9,3,2]
# lst1 = []
for j in range(len(lst)): #7
    m = lst[j]
    idx = j
    c = j
    for i in range(j,len(lst)):
        if lst[i]<m:
            m = lst[i]
            idx = c
        c += 1
    temp = lst[j]
    lst[j]= m
    lst[idx]=temp
print(lst)

[-5, 1, 2, 2, 3, 4, 7, 9]


# Functions in Python

In [ ]:
def PrintSuccess():
    print("I am Done.")
    print("Send me another task.")

PrintSuccess() #this is how we call any function.

I am Done.
Send me another task.


* The docstring allows us to write the description of the function but will never be executed. But it will always be available whenever uh need it.

In [ ]:
def printSuccess2():
    """ This function is doing nothing except printing a message.
    That message is "hello and this is my first time to use doc string in functions."
    """
    print("hello")

In [ ]:
printSuccess2??

Signature: printSuccess2()
Source:   
def printSuccess2():
    """ This function is doing nothing except printing a message.
    That message is "hello and this is my first time to use doc string in functions."
    """
    print("hello")
File:      c:\users\dell\appdata\local\temp\ipykernel_8360\2383231161.py
Type:      function

In [ ]:
len??

Signature: len(obj, /)
Docstring: Return the number of items in a container.
Type:      builtin_function_or_method

In [ ]:
help(printSuccess2)

Help on function printSuccess2 in module __main__:

printSuccess2()
    This function is doing nothing except printing a message.
    That message is "hello and this is my first time to use doc string in functions."



In [ ]:
printSuccess2()

hello


* Functions Input Arguements.

In [ ]:
def printMessage(msg):
    print(msg)
printMessage("Integrity")

Integrity


In [ ]:
def add(a,b):
    res = a+b
    print(f"The addition of {a} and {b} are {res}.")

add(b=56,a=4)

The addition of 4 and 56 are 60.


In [ ]:
def printMsg(msg):
    """The function prints the message supplied by the user or prints that msg
    is not in the form of string."""
    if isinstance(msg, str):
        print(msg)
    else:
        print(F"your input argument is not a string")
        print(f"Here is the type what you have given as an argument{type(msg)}.")

printMsg("resilient")
printMsg(56)

resilient
your input argument is not a string
Here is the type what you have given as an argument<class 'int'>.


In [ ]:
help(printMsg)

Help on function printMsg in module __main__:

printMsg(msg)
    The function prints the message supplied by the user or prints that msg 
    is not in the form of string.



In [ ]:
printMsg??

Signature: printMsg(msg)
Source:   
def printMsg(msg):
    """The function prints the message supplied by the user or prints that msg 
    is not in the form of string."""
    if isinstance(msg, str):
        print(msg)
    else:
        print(F"your input argument is not a string")
        print(f"Here is the type what you have given as an argument{type(msg)}.")
File:      c:\users\dell\appdata\local\temp\ipykernel_8360\2737676970.py
Type:      function

In [ ]:
y = 55656
x="MachineLearning"
printMsg(y)
printMsg(x)

your input argument is not a string
Here is the type what you have given as an argument<class 'int'>.
MachineLearning


* Multiple input arguements in python.(Functions)

In [ ]:
def mypow(a,b):
    """This function computes the power just like the built in function."""
    c = a**b
    print(c)


In [ ]:
mypow??

Signature: mypow(a, b)
Source:   
def mypow(a,b):
    """This function computes the power just like the built in function."""
    c = a**b
    print(c)
File:      c:\users\dell\appdata\local\temp\ipykernel_8360\425091463.py
Type:      function

In [ ]:
help(mypow)

Help on function mypow in module __main__:

mypow(a, b)
    This function computes the power just like the built in function.



In [ ]:
mypow(3,2)

9


Multiple args more than 2 args in a function or method.

In [ ]:
def chkTypes(a,b,c):
    """The function checks the datatypes of the inputs whether its giving the expected o/p or not.
    """
    if isinstance(a,(int,float)) and isinstance(b,(int,float)) and isinstance(c,(int,float)):
        print((a+b+c)**2)
    else:
        print("Error: the input argss are not of the expected types.")

In [ ]:
chkTypes(4,2,3)

81


In [ ]:
chkTypes(4,65,'association')

Error: the input argss are not of the expected types.


In [ ]:
chkTypes(4,65)

TypeError: chkTypes() missing 1 required positional argument: 'c'

In [ ]:
chkTypes(4,65,3,54)

TypeError: chkTypes() takes 3 positional arguments but 4 were given

* Ordering Multiple args in the function input.

In [ ]:
def f(a,b,c):
    print("A is:",a)
    print("B is:",b)
    print("C is:",c)
f(2,3,"xbox")

A is: 2
B is: 3
C is: xbox


In [ ]:
#Changing order.
f("box",3,4)

A is: box
B is: 3
C is: 4


In [ ]:
f(c = "game",a=2,b=3)

A is: 2
B is: 3
C is: game


* Output args and return type in Functions.

In [ ]:
# def add(x,y):
#  sumVal = x + y
#  # print(sum)
# add(3,8)
# print(sumVal)

NameError: name 'sumVal' is not defined

In [ ]:
def add(x,y):
  sumVal = x + y
  # print(sum)
  return sumVal
d = add(3,8)
print(f"The sum is:{d}")

The sum is:11


* Local variable is given much more priority for being accessed rather than Global variable.
* Function in python always return something if not the specified return then it will return None.

In [ ]:
varOutside = 2

In [ ]:
def g():
    varOutside = 5
    # print(varOutside)
    # return varOutside

In [ ]:
print(type(g()))

<class 'NoneType'>


In [ ]:
print(varOutside)

2


In [ ]:
def h():
    print('A')
    a = 3
    b = 4
    c = a+b
    print("something")
    print(c)
    return  c  # WORKS AS A BREAK STATEMENT WHICH IS USED TO RETURN VALUE INTO THE FUNCTION.
    print("B")
    print("C")




In [ ]:
print(type(h()))
print(h())  #Return the value of addition performed on the function.

A
something
7
<class 'int'>
A
something
7
7


In [ ]:
def res():
    a =4
    b = 7
    c = "Done"
    return  a,b,c

In [ ]:
x,y,z  = res()
print(x,y,z)

4 7 Done


* Taking n number of inputs in a function as a parameter.

In [ ]:
def add(*args):
    sum = 0
    for i in range(len(args)):
        sum += args[i]
    return sum

In [ ]:
print(add(3,4,5,2,12,343))

369


In [ ]:
def names(*args):
    for i in args:
        print(i)
names("jatin","gaurav","nanu","pihu")

jatin
gaurav
nanu
pihu


* Variable number of input args using ** as the parameter.

In [ ]:
def printAllVariableNames(**args):
    for i in args:
        print("Variable name is:",i,"and value is:",args[i])

In [ ]:
printAllVariableNames(a = 2,b = 'B',c = "ccc",y= 6.5)

Variable name is: a and value is: 2
Variable name is: b and value is: B
Variable name is: c and value is: ccc
Variable name is: y and value is: 6.5


In [ ]:
def Student(**kwargs):
    for name,id in kwargs.items():
      print(f"{name}:{id}")

s1 = Student(name = "Ramu",id = 4)
s2 = Student(id = 5,name = "Raj")
# s3 = Student("uvaish",8)

name:Ramu
id:4
id:5
name:Raj


* Default Values in Functions.

In [ ]:
#default values are the values which are given to a input when defining a function.

In [ ]:
def gg(s=4):
    print(s)

In [ ]:
gg()

4


In [ ]:
gg(34)

34


In [ ]:
l = [1,2,3,4]
l1 = l
l1[0] = -9
print(l)

[-9, 2, 3, 4]


In [ ]:
def ff(l=[1,2]):
    for i in l:
        print(i)

In [ ]:
l2 = [32,12,3]
ff()

1
2


In [ ]:
ff()

1
2


In [ ]:
ff(l2)

32
12
3


* Making modules in Python.

In [ ]:
def add(x,y):
  sumVal = x + y
  # print(sum)
  return sumVal
d = add(3,8)
print(f"The sum is:{d}")

In [ ]:
import sys
sys.path.append('D:\python files')

In [ ]:
import PYTHON_BAISCS2 as myfls

ModuleNotFoundError: No module named 'PYTHON_BAISCS2'

# Sorting list in Python


* Given a list of numbers i.e [1,2,4,-5,7,9,3,2] ,make another list that contains all the items in sorted order from min to max. i.e your result will be another list like [-5,1,2,2,3,3,7,9]

In [ ]:
lst =  [0,-8,5,23,76,7,53]
# lst1 = []
for j in range(len(lst)): #7
    m = lst[j]
    idx = j
    c = j
    for i in range(j,len(lst)):
        if lst[i]<m:
            m = lst[i]
            idx = c
        c += 1
    temp = lst[j]
    lst[j]= m
    lst[idx]=temp
print(lst)

[-8, 0, 5, 7, 23, 53, 76]


In [ ]:
def FindMin(L):
    m = L[0]
    idx = 0
    i = 0
    for x in L:
        if x<m:
            m = x
            idx = i
        else:
            pass
        i+=1
        return m,idx
a,b = FindMin([333,34,54,3,4,6,7])
print(a,b)

333 0


In [ ]:
lst = [4,34,54,-2,43,54]
for i in range(len(lst)):
    m = lst[i]
    idx = i
    c = i
    for j in range(i,len(lst)):
        if lst[j]<m:
            m = lst[j]
            idx = c
        c += 1
    temp = lst[i]
    lst[i] = m
    lst

[-2, 4, 34, 43, 54, 54]


In [ ]:
def swapValues(lst,idx1,idx2):
    temp = lst[idx1]
    lst[idx1] = lst[idx2]
    lst[idx2]= temp
    return lst
lst = [1,2,45,6,78,76]
res = swapValues(lst,1,3)
print(res)

[1, 6, 45, 2, 78, 76]


In [ ]:
'''def sortList(L):
    c = 0
    for i in L:
        m,idx = findMIn(L)
        L  = swapValues(L,c,idx)
        c += 1
    return L

print(L)'''

'def sortList(L):\n    c = 0\n    for i in L:\n        m,idx = findMIn(L)\n        L  = swapValues(L,c,idx)\n        c += 1\n    return L\n\nprint(L)'

* This is a Module we made in another notebook and imported it here but due to some reasons its not working.

In [ ]:
def checkIfNotNumeric(*args):
    for i in args:
        if not(isinstance(i,(int,float))):
            return False
    return True

# Strings In Python

In [ ]:
v = "Python is language"
s = "We are going to learn its framework i.e Django"
print(v+' and, '+s)

Python is language and, We are going to learn its framework i.e Django


In [ ]:
res = v+'OOPS CONCEPT'+s
print(res)

Python is languageOOPS CONCEPTWe are going to learn its framework i.e Django


In [ ]:
'''pri = 12
s = "The price of this book"
v = s+ 'is: '+ str(pri)
print(v)'''

TypeError: 'str' object is not callable

* STRING SLICING

In [ ]:
a = "Programming."
for i in enumerate(a):
    print(i)
print(a[3:9])
print(len(a))
print(len(a[2:5]))
print(a[3:-5])
print(a[5:-3])
print(a[::-1])

(0, 'P')
(1, 'r')
(2, 'o')
(3, 'g')
(4, 'r')
(5, 'a')
(6, 'm')
(7, 'm')
(8, 'i')
(9, 'n')
(10, 'g')
(11, '.')
grammi
12
3
gram
ammi
.gnimmargorP


In [ ]:
a = "Artificial"
print(a[0:7])
print("The length of the string is:",len(a))

b = "Intelligence"

print("The length of b is:",len(b))

print(b[0:6])

print(b[5:11])
#NEGATIVE INDEXING
print(b[0:len(b)-3])

print(b[0:-3]) #same as abv (KNOWN AS NEGATIVE SLICING)

print(b[-4:-2],"\n\n") #11-4 = 7

print(b)
print(b[-4:-5]) #this will not print due to wrogn assignment of slicing

print(b[-4:-3]) #The 2nd no should always be smaller than the firstone.


Artific
The length of the string is: 10
The length of b is: 12
Intell
ligenc
Intellige
Intellige
en 


Intelligence

e


* Some Functions of String

In [ ]:
a = "   abc def    hg; assgsdf    "
b = a.strip()
print(b)

abc def    hg; assgsdf


In [ ]:
a = "   fjroirjeijroiejfdsfjv      "  #removes the spaces before and after the string ends and prints the actual string
print(a.strip())

fjroirjeijroiejfdsfjv


In [ ]:
a = "JATINPASIJFEOIFJEOIJFOERIJFOIERJF"
'''converts all the upper case characters into Lowercase characters.'''
print(a.lower())

jatinpasijfeoifjeoijfoerijfoierjf


In [ ]:
a = "herewearelearningpythonbasics"
'''converts all the lowercase characters into upper case characters.'''
print(a.upper())

HEREWEARELEARNINGPYTHONBASICS


In [ ]:
a = "Here are we."
print(a.istitle())
print(a.replace("are","were"))
print(a.replace('.'," sitting."))

False
Here were we.
Here are we sitting.


In [ ]:
a = "Machine"
b = "learning"
c = "python is an easy language!!!"
d = "Dsa Is The Foundational Subject\n"
e = "pandas is a library"
f = " "

print(len(a))
print(a.islower())#checks whether the string is in lower-case.
print(a.isupper())
print(a.upper()) #converts string into upper case
print(a.lower())

print(c.replace("python","C++")) #used to replace the string by the new one(modification).

print(b.capitalize()) #used to capitalize the first letter of the string.

print(c.split()) #Creates a list of the given string if spaces are available.
print(c.split()[-2]) #Creates a list of the given string if spaces are available.

print(c.count("a")) #counts the freq of the given args in a string.

print(c.rstrip("!")) #removes the character present at the end of string.(post only)

print(c.endswith("!")) #checks whether the sentence or string ends with the same input.

print(c.endswith("is",4,29)) #same function but checks using slicing.

print(c.endswith("!",4,29)) #same function but checks using slicing.

print(c.startswith("python"))#case-sensative (checks the starting string comparing to input value.)

print(c.startswith("C++"))

print(c.find("is"))#calculates the first occurance of the string and returns the index value where it is stored.

print(c.find("easy"))

print(b.isalnum())#checks whether the string is alphanumeric or not.

print(c.isalnum())#c is not alphanumeric as it contains spaces btw it.

print(b.isalpha()) #determines only alphabets(a-z) [Non case-sensative].

print(c.isprintable())#determines whether the string can be printed or not.
#i.e if any specifier would be present it'll be considered as non-printable.

print(d.isprintable())#is non printable due to the presence of specifier in it.

print(f.isspace()) #checks only n only the space, seems useless.

print(e.istitle())#determines whether the first letter of every word is capital or not.

print(d.istitle())# since d has each n every word has first letter capital it is considered to be True.

print(e.title()) #capitalize first letter of each word.

print(a.swapcase())
print(b.swapcase()) #these both is used to swap the case.If upper then its converted into lower nd vice-versa.



7
False
False
MACHINE
machine
C++ is an easy language!!!
Learning
['python', 'is', 'an', 'easy', 'language!!!']
easy
4
python is an easy language
True
False
True
True
False
7
13
True
False
True
True
False
True
False
True
Pandas Is A Library
mACHINE
LEARNING


In [ ]:
a = "today is day 2 of learning python"
l = a.split(" ")
print(l)

['today', 'is', 'day', '2', 'of', 'learning', 'python']


In [ ]:
print(l[0],l[1])

today is


In [ ]:
a??

Type:        str
String form: today is day 2 of learning python
Length:      33
Docstring:  
str(object='') -> str
str(bytes_or_buffer[, encoding[, errors]]) -> str

Create a new string object from the given object. If encoding or
errors is specified, then the object must expose a data buffer
that will be decoded using the given encoding and error handler.
Otherwise, returns the result of object.__str__() (if defined)
or repr(object).
encoding defaults to sys.getdefaultencoding().
errors defaults to 'strict'.

In [ ]:
a.capitalize?

Signature: a.capitalize()
Docstring:
Return a capitalized version of the string.

More specifically, make the first character have upper case and the rest lower
case.
Type:      builtin_function_or_method

In [ ]:
a.upper?

Signature: a.upper()
Docstring: Return a copy of the string converted to uppercase.
Type:      builtin_function_or_method

In [ ]:
a.capitalize()

'Today is day 2 of learning python'

In [ ]:
a.count??

Docstring:
S.count(sub[, start[, end]]) -> int

Return the number of non-overlapping occurrences of substring sub in
string S[start:end].  Optional arguments start and end are
interpreted as in slice notation.
Type:      builtin_function_or_method

In [ ]:
print(a.count('j'))

0


In [ ]:
a = "Today is day 3 of learning python"
print('it' in a)
print('is' in a)


False
True


In [ ]:
"abc" =="abc"

True

In [ ]:
"abc"<"def"

True

In [ ]:
"jatin pasi" not in "gaurav"

True

In [ ]:
print("we are learning "string" here")

SyntaxError: invalid syntax. Perhaps you forgot a comma? (1078288962.py, line 1)

* ESCAPE SEQUENCE.

In [ ]:
print("we are learning \"string\" here")

we are learning "string" here


In [ ]:
print('we are learning "string" here')

we are learning "string" here


In [ ]:
print("we are \nnow on another line.")

we are 
now on another line.


In [ ]:
print("c:\name\drive")

c:
ame\drive


# Data Structures in Python.

In [ ]:
l = [1,2,4,55,'name',34.66,6,7,8]
tup= (1,2,4,5,'id',34.433,True)
dict = {'name':'jatin','age':20,'Branch':'AIML','sem':5}
s  = {1,2,4,5,6}
l2 = set(l)
print(type(l))
print(type(tup))
print(type(dict))
print(type(s))
print(l2)

In [ ]:
l = [1,2,4,5,'name',6]
print(l[1:4])  #SLICING.

[2, 4, 5]


# Some function in list.

In [ ]:
#Functions which are used to add an elements in a list.
l = [1,2,4,5,6,7,8,89,'name']
l.append(434)
print(l)
l.insert(4,300) #FIRST THE INDEX SHOULD BE MENTIONED.
print(l)
l2 = ['dict','tuple','set','list']
l.extend(l2) #concatinates two lists.
print(l)

[1, 2, 4, 5, 6, 7, 8, 89, 'name', 434]
[1, 2, 4, 5, 300, 6, 7, 8, 89, 'name', 434]
[1, 2, 4, 5, 300, 6, 7, 8, 89, 'name', 434, 'dict', 'tuple', 'set', 'list']


In [ ]:
# SOME FUNCTIONS TO REMOVE OR DELETE THE ELEMENTS FROM THE LIS.
l = [1,2,4455,23,545,65,98]
l.remove(2)  #REMOVES THE SPECIFIC ELEMENT FROM THE LIST.
print(l)
l.pop()  # REMOVES THE TOP ELEMENT FROM THE LIST.
print(l)
l.clear()  # CLEARS THE WHOLE LIST AND MAKE IT NULL.
print(l)

[1, 4455, 23, 545, 65, 98]
[1, 4455, 23, 545, 65]
[]


* More important Functions for arranging the list.

In [ ]:
l = [1,2,4455,2,2,2,23,545,65,98,545,65,98]
l.sort() #SORTS THE LIST IN ASSENDING ORDER.
print(l)
l.reverse()  #REVERSES THE LIST.
print(l)
print(l.count(2))
print(l.count(545))
print(l.count(98))
print(l.count(1))

[1, 2, 2, 2, 2, 23, 65, 65, 98, 98, 545, 545, 4455]
[4455, 545, 545, 98, 98, 65, 65, 23, 2, 2, 2, 2, 1]
4
2
2
1


In [ ]:
d = {'oldkey':'oldValue','name':'smarath'}
print(d)
del d['oldkey']  #del IS A DESTRUCTOR IN PYTHON AND INIT IS THE CONSTRUCTOR.
print(d)

{'oldkey': 'oldValue', 'name': 'smarath'}
{'name': 'smarath'}


* WAP when given 2 lists find the common elements in btw.

In [ ]:
size = int(input("Enter the size of the list:"))
lst = []
for i in range(size):
    ele = input(f"Enter the {i}th element:")
    lst.append(ele)
size2 = int(input("Enter the size of the list2:"))
lst2 = []
for j in range(size2):
    ele2 = input(f"Enter the {j}th element:")
    lst.append(ele2)
# print(lst)
lst3=[]
for c in lst:
    for d in lst2:
        if(d==c):
            lst3.append(d)
print(lst3)

Enter the size of the list: 2
Enter the 0th element: 1
Enter the 1th element: 2
Enter the size of the list2: 3
Enter the 0th element: 1
Enter the 1th element: 2
Enter the 2th element: 3


[]


In [ ]:
lst = [1,2,3,4,5,6]
lst1 = [2,4,6,7,8,9]
lst2= []
for i in lst:
    for j in lst1:
        if(i==j):
           lst2.append(i)
print(lst2)

[2, 4, 6]


# Strings

In [ ]:
my_str = 'Hello'
my_str2 = "hello"
my_str3 = """hello"""
print(my_str,my_str2,my_str3)

Hello hello hello


In [ ]:
my_str = input("Enter your name:")
print(my_str)

Enter your name: jatin asip


jatin asip


# string slicing

In [ ]:
my_str = "hello, ready to explore python!!"
#[starting pnt : ending : step]
print(my_str[4:16:2])# o ed o
print(my_str[12:30])# to explore python
print(my_str[:10])#0-9 index will execute.
print(my_str[::-1])
print(my_str.split(' '))
print(my_str.split('o'))

print(my_str.split('l'))

o ed o
 to explore python
hello, rea
!!nohtyp erolpxe ot ydaer ,olleh
['hello,', 'ready', 'to', 'explore', 'python!!']
['hell', ', ready t', ' expl', 're pyth', 'n!!']
['he', '', 'o, ready to exp', 'ore python!!']


WAP to count the number of words in a given string

In [ ]:
my_str = "how are you jatin"
space_count = 1
for i in my_str:
    if (i== " "):
     space_count +=1
print(f"The number of words are:{space_count}")


The number of words are:4


In [ ]:
# my_str = "how are you jatin"
# my_str2 = my_str.split(' ')
# my_set = set(my_str2)
# space_count = 1
# for i in my_set:

#      space_count +=1
# print(f"The number of words are:{space_count}")


The number of words are:5


2. WAP to reverse a given string withoyut using slicing or inbuilt techniques.
3. METHOD =1

In [ ]:
my_str = input("Enter the string:")
n = len(my_str)
print(type(my_str))
rev_str = ""
for i in range(n-1,-1,-1):
    rev_str += my_str[i]
print(rev_str)
print(type(rev_str))

print("DONE")


Enter the string: Jatin


<class 'str'>
nitaJ
<class 'str'>
DONE


In [ ]:
my_str = "Python"
my_list = list(my_str)
i = 0
j = len(my_str)-1
while(i<=j):
   my_list[i],my_list[j] = my_list[j],my_list[i]
   i+=1
   j-=1
# rev_str = str(my_list)
# print(rev_str)
print(str(my_list))


['n', 'o', 'h', 't', 'y', 'P']


WAP to count the number of duplicates in a given string.


In [ ]:
str1 = "Python Programming"
count = 0
for j in str1:
    for i in str1:
            if(j==i):
              count+=1
print(f"No. of duplicates:{count-len(str1)}")

No. of duplicates:12


In [ ]:
str1 = "Python Programming"
count = 0
for i in range(0,len(str1)):
    for j in range(0,len(str1)):
        if(i==j):
            continue
        elif(str1[i]==str1[j]):
            count +=1
print(f"The no. of duplicates are:{count}")

The no. of duplicates are:12


In [ ]:
str1 = "python programming"
count = 0
for i in range(0,len(str1)):
    for j in range(i+1,len(str1)):
        if (str1[i]==str1[j]):
            count +=1
print(count)

6


QUESTIONS:-
1. WAP to check a string is palindrome or not
2. WAP to check a string is anagram or not.

In [ ]:
%whos

Variable      Type    Data/Info
-------------------------------
a             int     5
count         int     6
i             int     17
j             int     17
list1         list    n=8
my_list       list    n=6
my_set        set     {'you', 'jatin', 'how', 'are'}
my_str        str     Python
my_str2       list    n=4
my_str3       str     hello
n             int     5
rev_str       str     ['n', 'o', 'h', 't', 'y', 'P']
space_count   int     5
str1          str     python programming


* Palindrome number

In [ ]:
str = input("Enter the string:")
rev_str = ""
n = len(str)
for i in range(n-1,-1,-1):
    rev_str += str[i]
if(rev_str == str):
    print(f"The string is Palindrome.")
else:
    print(f"The string is not Palindrome.")

Enter the string: madam


The string is Palindrome.


# Lists

In [ ]:
x = [19,10.5,False,"python",(4+3j)]
x.append(45)
print(x)
print(type(x))

[19, 10.5, False, 'python', (4+3j), 45]
<class 'list'>


Functions in List.

In [ ]:
#ADDING ELEMENTS IN LIST USING THREE DIFFERENT FUNCTIONS.
lst = [10,20,30]
#using append function--> add the element at the end of list.
print("Before append function:",lst)
lst.append(40)
lst.append(50)
print("After append function.",lst)
#using insert function--> add the element at the given position.
lst.insert(2,60)
print("After insert function.",lst)
#using extend function-->adds iterables
lst1 = [70,80,90]
lst.extend(lst1)
print("After using extend function.",lst)

Before append function: [10, 20, 30]
After append function. [10, 20, 30, 40, 50]
After insert function. [10, 20, 60, 30, 40, 50]
After using extend function. [10, 20, 60, 30, 40, 50, 70, 80, 90]


Functions to remove the data from list

In [ ]:
lst = [10,20,30,40,50,50,60,70]
print("Before delete function:",lst)
#using remove function--> Delete the specific element.
lst.remove(50)
print("After remove function:",lst)

#using pop()--> deletes the data from the end.
lst.pop()
print("After pop function:",lst)

#using clear()--> delete all the data from list.
lst.clear()
print("List after clear function",lst)

Before delete function: [10, 20, 30, 40, 50, 50, 60, 70]
After remove function: [10, 20, 30, 40, 50, 60, 70]
After pop function: [10, 20, 30, 40, 50, 60]
List after clear function []


More important Functions for arranging the list.

In [ ]:
lst = [1,4,53,6,3,9]
print("Before sorting:",lst)

#using sort()--> used to sort the list in increasing order.
lst.sort()
print("After sorting:",lst)

#using reverse ()--> used to reverse the list.
lst.reverse()
print("After reverse function",lst)

Before sorting: [1, 4, 53, 6, 3, 9]
After sorting: [1, 3, 4, 6, 9, 53]
After reverse function [53, 9, 6, 4, 3, 1]


In [ ]:
lst = [1,1,1,1,1,1,2,2,2,3,4,5,6,1,2]
print(lst.count(1)) # gives the freq of any specific number.
print(lst.count(2))
print(lst.count(3))
print(lst.count(4))
print(lst.count(5))

7
4
1
1
1


Taking list from user

In [ ]:
#WAP to create a list.
size = int(input("Enter the size of the list:"))
lst = []
for i in range(size):
    elem = int(input("Enter the element:"))
    lst.append(elem)
print(lst)

Enter the size of the list: 5
Enter the element: 1
Enter the element: 2
Enter the element: 3
Enter the element: 4
Enter the element: 5


[1, 2, 3, 4, 5]


In [ ]:
#WAP to create a 2D list.
row = int(input("Enter the row size:"))
col = int(input("Enter the column size:"))
lst = [[i for i in range(5)]]
for i in range(row):
    for j in range(col):
        ele = int(input("Enter the element:"))
        lst.append(ele)
print(lst)

Enter the row size: 2
Enter the column size: 3
Enter the element: 1
Enter the element: 2
Enter the element: 3
Enter the element: 4
Enter the element: 5
Enter the element: 6


[[0, 1, 2, 3, 4], 1, 2, 3, 4, 5, 6]


1. WAP to FIND THE LENGTH OF THE GIVEN LIST.

In [ ]:
lst = [1,2,3,4,5,6]
# n = len(lst)
count = 0
for i in lst:
    count +=1
print(count)

6


2. WAP to calculate the sum of all the elements in the list.


In [ ]:
size = int(input("Enter the size of list:"))
lst =[]
sum = 0
for i in range(size):
    ele = int(input("Enter the elements:"))
    lst.append(ele)
#Approach 1:
for j in lst:
    sum = sum + j
print(sum)

Enter the size of list: 5
Enter the elements: 2
Enter the elements: 3
Enter the elements: 4
Enter the elements: 1
Enter the elements: 2


12


SETS IN PYTHON

In [ ]:
#ADD AND UPDATE FUNCTION.
set1 = {1,2,3,4,5,6}
print("Before add method:",set1)
#using add method-->
set1.add(10)
print("After add method:",set1)

#Using update()--> adds iterable.
set2 = {20,21,22}
set1.update(set2)
print("After update function:",set1)

Before add method: {1, 2, 3, 4, 5, 6}
After add method: {1, 2, 3, 4, 5, 6, 10}
After update function: {1, 2, 3, 4, 5, 6, 10, 20, 21, 22}


In [ ]:
set1 = {1,1,2,2,3,4,3,1,1,2}
print(set1)
#there can be no duplicates.

{1, 2, 3, 4}


In [ ]:
set1 = {1,4,2,5,7,9}
print(set1)
#always gives data in sorted order.

{1, 2, 4, 5, 7, 9}


In [ ]:
set1 = {1,5,8,9,3,4}

set1.remove(8)
print(set1)

set1.discard(3)
print(set1)

set1.clear()
print(set1)

{1, 3, 4, 5, 9}
{1, 4, 5, 9}
set()


In [ ]:
set1 = {1,2,3,4}
set2 = {3,4,5,6,7}
set1.union(set2)

{1, 2, 3, 4, 5, 6, 7}

In [ ]:
set1.difference(set2)

{1, 2}

In [ ]:
set1.symmetric_difference(set2)

{1, 2, 5, 6, 7}

In [ ]:
set1.intersection(set2)

{3, 4}

1. [ ]--> list
2. { }-->Dictionary
3. ( )--> tuple

In [ ]:
size = int(input("Enter the size:"))
my_set = set()
for i in range(size):
    ele = int(input("Enter the elements :"))
    my_set.add(ele)
print(my_set)

Enter the size: 5
Enter the elements : 2
Enter the elements : 3
Enter the elements : 1
Enter the elements : 6
Enter the elements : 3


{1, 2, 3, 6}


3. WAP to remove all occurance of a specific elements.

In [ ]:
size = int(input("Enter the size:"))

lst=[]
new_lst=[]
for i in range(size):
    ele = int(input("Enter the element:"))
    lst.append(ele)

key = int(input("Enter the element to be removed"))
for i in lst:
    if (key!=i):
        new_lst.append(i)
print(new_lst)

Enter the size: 4
Enter the element: 1
Enter the element: 2
Enter the element: 3
Enter the element: 4
Enter the element to be removed 3


[1, 2, 4]


4. WAP when given 2 lists find the common elements in btw.

In [ ]:
lst1 = [2,3,4,5,6,1]
lst2 = [3,4,6,7,9,8,2,10]
newlst = []
for i in lst1:
    for j in lst2:
        if(i==j):
          newlst.append(j)
print(newlst)

[2, 3, 4, 6]


5. WAP where you have given a list of words count the freq of each word

In [ ]:
lst = ["apple","is","red","an","apple","a","day","keeps","doctor","away"]
j=1
while(j<len(lst)):
    count = 1

    for i in range(j+1,len(lst)):
      if(lst[j]==lst[i]):
         count += 1
    print(lst[j]," ",count)
    j+=1


is   1
red   1
an   1
apple   1
a   1
day   1
keeps   1
doctor   1
away   1


* ANAGRAM PROBLEM

In [ ]:
#USING LIST METHOD.
word1 = input("Enter the first word: ")
word2 = input("Enter the second word: ")


new1 = list(word1)
new2 = list(word2)
new1.sort()
new2.sort()

# print(new1)
# print(new2)
if new1 == new2:

    print(f"The words {word1} and {word2} are anagrams.")
else:
     print(f"The words {word1} and {word2} are not anagrams.")


Enter the first word:  ujra
Enter the second word:  uajr


The words ujra and uajr are anagrams.


In [ ]:
word1 = input("Enter the first word:")
word2 = input("Enter the second word:")
newWord1 = sorted(word1)
newWord2 = sorted(word2)
if newWord1 == newWord2:
    print(f"The words {word1} and {word2} are anagrams.")
else:

    print(f"The words {word1} and {word2} are not anagrams.")

Enter the first word: urja
Enter the second word: raju


The words urja and raju are anagrams.


# OOP's in Python

In [ ]:
#Rule for defining a class.
#class ClassName:
class Student:
     clg = "Global"


In [ ]:
class Car:
    wheels = 4

    def __init__(self,color):
      print("The address from self:",self)
      self.color = color
    def disp(self):
        print(self.color)

c1 = Car("black")
print("Address from object",c1)
c2 = Car("Chocolate")
print("Address from",c2)
print(c1.wheels)
c1.disp()
print(c2.wheels)
c2.disp()

The address from self: <__main__.Car object at 0x0000022D3D76F950>
Address from object <__main__.Car object at 0x0000022D3D76F950>
The address from self: <__main__.Car object at 0x0000022D3D76FDD0>
Address from <__main__.Car object at 0x0000022D3D76FDD0>
4
black
4
Chocolate


* WAP to create a class student with attributes id,name,college and display all the attributes of the particular student details.

In [ ]:
class Student:
    def __init__(self,name,id,clg):
        self.name = name
        self.id = id
        self.clg = clg

    def disp(self):
            print("The name of student is:",self.name)
            print("The id of student is:",self.id)
            print("The college of student is:",self.clg)
s1 = Student("Raju",2,"global")
s2 = Student("shubhi",3,"global")
s3 = Student("vedant",4,"global")
s4 = Student("cheenu",5,"global")
s5 = Student("jatin",6,"global")
s1.disp()
s2.disp()
s3.disp()
s4.disp()
s5.disp()

The name of student is: Raju
The id of student is: 2
The college of student is: global
The name of student is: shubhi
The id of student is: 3
The college of student is: global
The name of student is: vedant
The id of student is: 4
The college of student is: global
The name of student is: cheenu
The id of student is: 5
The college of student is: global
The name of student is: jatin
The id of student is: 6
The college of student is: global


WAP to create a class Animal with properties type,color,num of legs,to disp its behaviour eats,walk,sleep

In [ ]:
class Animal:
    def __init__(self,type,color):
        self.type = type
        self.color = color

    def disp(self):
        print("The type is:",self.type)
        print("The color is:",self.color)

tiger = Animal("Carnivore","yellow")
dog = Animal("Omnivores","white")
dog.disp()
tiger.disp()

The type is: Omnivores
The color is: white
The type is: Carnivore
The color is: yellow


Inheritence in python

In [ ]:
class A:
    def disp(self):
        print("Display A")

class B(A):

    pass

objB = B()
objB.disp()
objA = A()
objA.disp()

Display A
Display A


In [ ]:
class GrandFather:
    def property(self):
        print("cash+land+gold")

class Father(GrandFather):
    pass


class Son(Father):
    pass


class GrandSon():
    pass

s = Son()
s.property()
f = Father()
f.property()
gf = GrandFather()
gf.property()
gs = GrandSon()
gs.property()

cash+land+gold
cash+land+gold
cash+land+gold


* Multilevel Inheritence

In [ ]:
class Animal:
    def eat(self):
        print("Eating")
class Cow(Animal):
    def walk(self):
        print("Cow is walking")
class Tiger(Animal):
    def run(self):
        print("Tiger Running")

class Bear(Animal):
    def sleep(self):
        print("Bear sleeping")
c = Cow()
c.eat()
c.walk()

Eating
Cow is walking


* Multiple Inheritence

In [ ]:
class Animal:
    def eat(self):
        print("Eating")

class Bird:
    def fly(self):
        print("Flying")

class X(Animal,Bird):
    pass

x1 = X()
x1.fly()
x1.eat()


Flying
Eating


* Method OverRiding

In [ ]:
class Parent:
    def property(self):
        print("cash+land+gold")
    def marry(self):
        print("Trisha")

class Child(Parent):
    def marry(self):
        print("Sam")

c = Child()
c.property()
c.marry()

cash+land+gold
Sam


* Encapsulation

In [ ]:
class Bank:
    def __init__(self,balance):
        self.__balance = balance  #_ using this it became protected.
        #__ defines private.

objBank = Bank(1000)
print(objBank.balance)

AttributeError: 'Bank' object has no attribute 'balance'

In [ ]:
def disp(x):
    for i in range(x):
        return i

print(disp(5))

In [ ]:
def disp(start,end):
    for i in range(start,end+1):
        print(i)
    pass
disp(11,16)

11
12
13
14
15
16


In [ ]:
# def disp(*args)
#taking multiple args as input.
#def __del__() destructor

WAP to create a class Animal with properties type,color,num of legs,to disp its behaviour eats,walk,sleep

In [ ]:
class Animal:
    def __init__(self,type,color):
        self.type = type
        self.color = color

    def disp(self):
        print("The type is:",self.type)
        print("The color is:",self.color)

class Dog(Animal):
    def eat(self):
     print("the dog Is eating Biscuit.")
    def walk(self):
        print("The dog is walking.")

class tiger(Animal):
    def eat(self):
     print("the tiger Is eating Flesh.")
    def run(self):
        print("The tiger is running")

t = tiger(Animal,'Yellow')
t.disp()
t.eat()
t.run()
d = Dog(Animal,'White')
d.disp()
d.eat()
d.walk()


The type is: <class '__main__.Animal'>
The color is: Yellow
the tiger Is eating Flesh.
The tiger is running
The type is: <class '__main__.Animal'>
The color is: White
the dog Is eating Biscuit.
The dog is walking.


1. Bank Account System - You are designing a bank account management system. Each account has an account holder's name,balance, and account type (Savings/Current)
2. Use inheritance to create a SavingsAccount and CurrentAccount class from a common BankAccount class.
Implement polymorphism for a method calculate_interest() that computes interest differently for savings and current accounts.
Ensure account numbers are unique for each object using a class attribute.
Can you write a program to demonstrate this?

In [ ]:
class Bank:

    def __init__(self,name,bal,accType):
        self.name = name
        self.bal = bal
        self.accType = accType

    def disp(self):
        print(f"The name of candidate is:",self.name)
        print(f"The Balance of candidate is:",self.bal)
        print(f"The Account Type of candidate is:",self.accType)

    def Calculate_Interest(self,prin,time,rate):
           # Interest = P * R * T,
            self.prin = prin
            self.time = time
            self.rate = rate
            self.Int = Int
            Int = prin*rate*time
            print(f"The Interest calculated is:{Int}")
c1 = Bank("Jatin",45700000,"Savings")
c1.disp()
c1.Calculate_Interest(1000,5,4)

The name of candidate is: Jatin
The Balance of candidate is: 45700000
The Account Type of candidate is: Savings


UnboundLocalError: cannot access local variable 'Int' where it is not associated with a value

In [ ]:
def add(x,y):
    return x+y
def add(x,y,z):
    return x+y+z
res = add(5,6,1)
print(res)

12


In [ ]:
def add(*args):
    res = 0
    for i in args:
        res += i
    return res

finalValue = add(3,4,5,6,1)
print(finalValue)

19


In [ ]:
def add(*args):
    res = 0
    for i in args:
        res += i
    return res

finalValue = add(3,4,5,6,1)
print(finalValue)

19


In [ ]:
def Student(**kwargs):
    for name,id in kwargs.items():
      print(f"{name}:{id}")

s1 = Student(name = "Ramu",id = 4)
s2 = Student(id = 5,name = "Raj")
# s3 = Student("uvaish",8)

name:Ramu
id:4
id:5
name:Raj


# Lambda Function

In [ ]:
res = lambda x,y:x*y
print(res(3,4))

12


In [ ]:
even = lambda num:num%2 == 0
print(even(23))

False


WAP to find product of 4 numbers and check whether the result is multiple of 5 or not.

In [ ]:
pro = lambda a,b,c,d:a*b*c*d
d = pro(1,5,2,1)
chk = lambda d:d%5==0
print(d)
print(chk(d))

10
True


In [ ]:
def add(x,y,operation):
    return operation(x,y)

res = add(5,6,lambda x,y:x+y)
print(res)


11


In [ ]:
def add(x,y,operation1,operation2):
    return operation1(x,y),operation2(x,y)

res = add(5,6,lambda x,y:x+y,lambda x,y:x*y)
print(res)


(11, 30)


create a function that has 2 function in it even and odd return the o/p for a number in form of tuples.

In [ ]:
def Number(x,even,odd):
    return even(x),odd(x)

res = Number(24,lambda x:x%2==0,lambda x:x%2!=0)
print(res)

(True, False)


In [ ]:
my_lst = [1,2,3,4]
my_lst2 = list(map(lambda x:x**2,my_lst))
print(my_lst2)

[1, 4, 9, 16]


WAP a program to create a list of 5 numbers and return their remainders after dividing it by 2 in form of list.

In [ ]:
size = int(input("Enter the size of list:"))
lst = []
for i in range(size):
    ele = int(input(f"Enter the {i}th elements of list:"))
    lst.append(ele)

lst2 = list(map(lambda x:x%2,lst))
print(lst2)

Enter the size of list: 2
Enter the 0th elements of list: 23
Enter the 1th elements of list: 45


[1, 1]


In [ ]:
lst = [1,2,3,4]
lst2 = list(filter(lambda x:x%2==0,lst))
lst2

[2, 4]

In [ ]:
size = int(input("Enter the size of list:"))
lst = []
for i in range(size):
    ele = int(input(f"Enter the {i}th elements of list:"))
    lst.append(ele)

lst2 = list(filter(lambda x:x%3==0,lst))
lst2

Enter the size of list: 5
Enter the 0th elements of list: 12
Enter the 1th elements of list: 23
Enter the 2th elements of list: 33
Enter the 3th elements of list: 42
Enter the 4th elements of list: 66


[12, 33, 42, 66]

In [ ]:
from functools import reduce
lst = [1,2,3,4,5]
lst2 = reduce(lambda x,y:x*y,lst)
lst2

120

# Generator in python


In [ ]:
def disp(x):
    for i in range(1,x+1):
        yield i

res = disp(5)
print(next(res))
print(next(res))
print(next(res))
print(next(res))

1
2
3
4


In [ ]:
def even(n):
    for i in range(1,n+1):
        if(i%2==0):
            yield i
res = even(10)

for i in even(10):
    print(i)

2
4
6
8
10


# Most important concept of python Regular Expression Regex

* wap to check characters starting from a ending with b.

In [ ]:
# . used to ignore the btw characters.
import re
res = re.findall(r'a.b','abc adb cvb aeb abcdefb')
print(res)

['adb', 'aeb']


In [ ]:
"^ checks whether the str contains the starting word as given in function."
import re
res = re.findall(r'^Hello','Hello worldHello hi hiworld Hello World')
print(res)

['Hello']


In [ ]:
"$ checks whether the str contains the starting word as given in function."
import re
res = re.findall(r'Hello$','Hello worldHello hi hiworld Hello')
print(res)

['Hello']


In [ ]:
'*'
import re
res = re.findall(r'ca*t','cat caaat caat cbt taac,ct')
print(res)

['cat', 'caaat', 'caat', 'ct']


In [ ]:
'+'
import re
res = re.findall(r'cat','cat caaat caat cbt taac,ct')
print(res)

['cat']


In [ ]:
'?'
import re
res = re.findall(r'ca?t','cat caaat caat cbt taac,ct')
print(res)

['cat', 'ct']


In [ ]:
'{n}'
import re
res = re.findall(r'a{1}','cat caaat caat cbt taac,ct')
print(res)

['a', 'a', 'a', 'a', 'a', 'a', 'a', 'a']


In [ ]:
'{n,}'
import re
res = re.findall(r'a{2,}','cat caaat caat cbt taac,ct')
print(res)

['aaa', 'aa', 'aa']


In [ ]:
'{n,m}'
import re
res = re.findall(r'a{1,3}','cat caaat caat cbt taac,ct')
print(res)

['a', 'aaa', 'aa', 'aa']


In [ ]:
'[]'
import re
res = re.findall(r'[caa]','cat caaat caat cbt taac,ct')
print(res)

['c', 'a', 'c', 'a', 'a', 'a', 'c', 'a', 'a', 'c', 'a', 'a', 'c', 'c']


In [ ]:
'\d'
import re
res = re.findall(r'\d+','124 cat caaat caat cbt 45 taac,ct')
print(res)

['124', '45']


# Dictionary


In [ ]:
#syntax
#dict = {key1:value1,key2:value2:key3:value3......,keyN:valueN}


In [ ]:
student = {
    "name":"aman",
    "age":21,
    "course":"AI/ML"
}
# student["address"]="Jabalpur"
student["age"]=16
print(student)
print(student["name"])
print(student.get("name"))
#print(student["address"])
print(student.get("address"))
print(student.get("address","not")) #most Preferable.
print(student.get("name","Not Available")) #most Preferable.

{'name': 'aman', 'age': 16, 'course': 'AI/ML'}
aman
aman
None
not
aman


In [ ]:
student.pop("course")

'AI/ML'

In [ ]:
print(student)

{'name': 'aman', 'age': 16, 'address': 'Jabalpur'}


In [ ]:
del student["age"]
print(student)

{'name': 'aman', 'address': 'Jabalpur'}


In [ ]:
student.popitem()
student.clear()
print(student)

{}


In [ ]:
dict = {'a':1,'b':2,'a':1,'c':3,'d':4,'e':5,'b':6}
for key in dict:
    print(key)

for value in dict.values():
    print(value)

for key,value in dict.items():
    print(f"{key}:{value}")

a
b
c
d
e
1
6
3
4
5
a:1
b:6
c:3
d:4
e:5


* WAP to count te frequency of word?

In [ ]:
word = "Hello Java Hello Python"
word_count ={}

for words in word.split():
    word_count[words] = word_count.get(words,0)+1

print(word_count)

{'Hello': 2, 'Java': 1, 'Python': 1}


In [ ]:
str = "a,b,a,c,b,d,a"
dict = {}
for i in str.split(","):
    dict[i] = dict.get(i,0)+1

print(dict)
print(dict['a'])

{'a': 3, 'b': 2, 'c': 1, 'd': 1}
3


* WAP to print the majority element in the list.

In [ ]:
lst = [1,2,3,2,2,2,2,1,3,4,1,2,2,2,2,2,2]
n = len(lst)
dict = {}

for i in lst:
    dict[i]=dict.get(i,0)+1
for key,value in dict.items():
    if(value>n//2):
        print(key)
        break

2


* majority 2 = WAP to find the majority element.

In [ ]:
lst = [1,2,3,2,2,2,2,2,2,2,2,2,2,1,3,4,1,2,2,2,2,2,2,4,4,4,4,4,4,4,4,4,4,4,4,4,4,44,4,4,4,4]
n = len(lst)
dict = {}
lst1 =[]

for i in lst:
    dict[i] = dict.get(i,0)+1

for key,value in dict.items():
    if(value>n//3):
        lst1.append(key)


print(lst1)


[2, 4]


* WAP to count the frequency of characters in a given string

In [ ]:
word = "remmember"
word_count ={}

for words in word:
    word_count[words] = word_count.get(words,0)+1

print(word_count)

{'r': 2, 'e': 3, 'm': 3, 'b': 1}


# Dictionary Comprehension

In [ ]:
dict = {1:1,2:2,3:3,4:4}
for key,value in dict.items():
    dict[key] = value**2

for key,value in dict.items():
    print(f"{key}:{value}")

1:1
2:4
3:9
4:16


In [ ]:
dict = {x:x**2 for x in range(1,5)}
print(dict)

{1: 1, 2: 4, 3: 9, 4: 16}


* WAP to swap key and values

In [ ]:
dict = {'a':1,'b':2,'c':3,'d':4}
dict1 ={}
for key,value in dict.items():
     print(f"{value}:{key}")
print(dict)

1:a
2:b
3:c
4:d
{'a': 1, 'b': 2, 'c': 3, 'd': 4}


In [ ]:
dict = {'a':1,'b':2,'c':3,'d':4}
dict1 ={}

for key,value in dict.items():
    dict1[value]=key

print(dict1)

{1: 'a', 2: 'b', 3: 'c', 4: 'd'}


* WAP to find common keys into two dictionaries

In [ ]:
a = {'a':1,'b':2,'c':3,'d':4,'e':5,'f':6}
b = {'abc':454,'b':343,'cds':342,'d':454,'ewe':523,'fhg':611,'e':21}
lst = []
for keys,value in a.items():
    for i,j in b.items():
        if(keys==i):
         lst.append(keys)
print(lst)

['b', 'd', 'e']


# List Comprehension

In [ ]:
n = int(input("Enter the size of list:"))
lst = [int(input("Enter the element:")) for i in range(n)]
print(lst)

Enter the size of list: 4
Enter the element: 12
Enter the element: 32
Enter the element: 22
Enter the element: 1


[12, 32, 22, 1]


In [ ]:
row = int(input("Enter the number of rows:"))
col = int(input("Enter the number of columns:"))
lst = [[int(input("Enter the element:")) for i in range(col)]for j in range(row)]
print(lst)

Enter the number of rows: 2
Enter the number of columns: 2
Enter the element: 1
Enter the element: 3
Enter the element: 4
Enter the element: 5


[[1, 3], [4, 5]]


* WAP to create two matrix and find the addition of the matrix.

In [ ]:
row1 = int(input("Enter the number of rows1:"))
col1 = int(input("Enter the number of columns1:"))
lst1 = [[int(input("Enter the element:")) for i in range(col1)]for j in range(row1)]
print(lst1)
row2 = int(input("Enter the number of rows2:"))
col2 = int(input("Enter the number of columns2:"))
lst2= [[int(input("Enter the element:")) for i in range(col2)]for j in range(row2)]
print(lst2)
lst = [[lst1[i][j] + lst2[i][j] for j in range(len(lst1[0]))]for i in range(len(lst1))]
print("The sum of two lists are:",lst)


Enter the number of rows1: 2
Enter the number of columns1: 2
Enter the element: 1
Enter the element: 2
Enter the element: 3
Enter the element: 4


[[1, 2], [3, 4]]


Enter the number of rows2: 2
Enter the number of columns2: 2
Enter the element: 6
Enter the element: 6
Enter the element: 5
Enter the element: 6


[[6, 6], [5, 6]]
The sum of two lists are: [[7, 8], [8, 10]]


# Join Function
->To convert the list into the string.

In [ ]:
str = "Hi, welcome to the python classes"
lst = str.split()
lst.reverse()
str2= " ".join(lst)
print(lst)
print(str2)

['classes', 'python', 'the', 'to', 'welcome', 'Hi,']
classes python the to welcome Hi,


# *Introduction to Pandas and Numpy*

In [ ]:
import numpy as np
import pandas as pd
print(numpy.__version__)
print(pandas.__version__)


1.26.4
2.1.4


In [ ]:
import numpy as np
lst = np.array([1,2,3,4,5])
print(lst)

[1 2 3 4 5]


In [ ]:
row = int(input("Enter the number of rows:"))
col = int(input("Enter the number of columns:"))
lst = [[int(input("Enter the element:")) for i in range(col)]for j in range(row)]
arr = np.array(lst)
print(arr)

Enter the number of rows: 3
Enter the number of columns: 3
Enter the element: 1
Enter the element: 2
Enter the element: 3
Enter the element: 4
Enter the element: 5
Enter the element: 6
Enter the element: 7
Enter the element: 8
Enter the element: 9


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
import random
arr = np.zeros((2,2))
print(arr)
arr2 = np.ones((2,2))
print(arr2)

arr3 = np.random.rand(2,2)
print(arr3)

[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]]
[[0.27918113 0.75124792]
 [0.56296558 0.83629147]]


In [ ]:
arr = np.arange(1,16,2)
print(arr)

[ 1  3  5  7  9 11 13 15]


In [ ]:
arr = np.linspace(1,2,6) #Takes in 6 equal fragments.
print(arr)

[1.  1.2 1.4 1.6 1.8 2. ]


In [ ]:
arr = np.linspace(1,2,3) #Takes in 6 equal fragments.
print(arr)

[1.  1.5 2. ]


In [ ]:
arr = np.array([1,2,3,4,5])
print(arr+5)
print(arr*2)

[ 6  7  8  9 10]
[ 2  4  6  8 10]


In [ ]:
arr = np.array([1,2,3,4])
arr1 = np.array([6,6,7,8])
print("The sum of two arrays:",arr+arr1)
print("The product of two arrays:",arr*arr1)

The sum of two arrays: [ 7  8 10 12]
The product of two arrays: [ 6 12 21 32]


In [ ]:
# row1 = int(input("Enter the number of rows1:"))
col1 = int(input("Enter the number of columns1:"))
lst1 = [[int(input("Enter the element:")) for i in range(col1)]for j in range(row1)]
print(lst1)
row2 = int(input("Enter the number of rows2:"))
col2 = int(input("Enter the number of columns2:"))
lst2= [[int(input("Enter the element:")) for i in range(col2)]for j in range(row2)]
arr = np.array(lst1)
arr1 = np.array(lst2)
print(lst2)
print("The sum of 2 arrays are:",arr+arr1)
print("The sum of 2 arrays are:",arr*arr1)

Enter the number of columns1: 1
Enter the element: 1
Enter the element: 1


[[1], [1]]


Enter the number of rows2: 1
Enter the number of columns2: 1
Enter the element: 1


[[1]]
The sum of 2 arrays are: [[2]
 [2]]
The sum of 2 arrays are: [[1]
 [1]]


In [ ]:
arr = np.array([10,100,1000])
print(np.sqrt(arr))
print(np.sin(arr))
print(np.log(arr)) #Base 2(natura log)

[ 3.16227766 10.         31.6227766 ]
[-0.54402111 -0.50636564  0.82687954]
[2.30258509 4.60517019 6.90775528]


In [ ]:
arr = np.array([1,2,3,4,5,6,7])
print(np.mean(arr))
print(np.std(arr)) #mean/2.
print(np.sum(arr))
print(arr[arr>3])

4.0
2.0
28
[4 5 6 7]


* WAP to create a numpy array of numbers from 1-9 and reshape it into a 3X3 matrix

In [ ]:
# col1 = int(input("Enter the number of columns1:"))
# lst1 = [[int(input("Enter the element:")) for i in range(col1)]for j in range(row1)]
# print(lst1)
# row2 = int(input("Enter the number of rows2:"))
# col2 = int(input("Enter the number of columns2:"))
# lst2= [[int(input("Enter the element:")) for i in range(col2)]for j in range(row2)]

[1 2 3 4 5 6 7 8 9]


In [ ]:
#1st Approach.
# lst = [x for x in range(1,10)]
arr = np.arange(1,10).reshape(3,3)
print(arr)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
#2nd approach.
lst = [x for x in range(1,10)]
arr = np.array(lst).reshape(3,3)
print(arr)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


* WAP to find the max and min value in an array.
  

In [ ]:
lst = [x for x in range(1,10)]
# arr = np.min(lst)
# arr1 = np.max(lst)
print("The minimum element is:",np.min(lst))
print("The maximum array is",np.max(lst))

The minimum element is: 1
The maximum array is 9


* WAP to find the transpose of the matrix and inverse.

In [ ]:
arr = np.array([[1,2],[3,4]])
print(np.transpose(arr))
det = np.linalg.det(arr)
print(det)
if(det!=0):
    inv = np.linalg.inv(arr)
    print(inv)
else:
    print("Inverse is not possible")
# print(np.linalg.inv(arr))

[[1 3]
 [2 4]]
-2.0000000000000004
[[-2.   1. ]
 [ 1.5 -0.5]]


* WAP to convert 2X2 matrix into 1d)

In [ ]:
arr = np.array([[1,2],[3,4]])
arr1 = np.array(arr).flatten()
print(arr1)

[1 2 3 4]


* Split a 1D array in 3 parts.

In [ ]:
arr = [i for i in range(1,12)]
parts = np.array_split(arr,3)
print(parts)
for i,j in enumerate(parts,1):
    print(f"part {i}:",j)

[array([1, 2, 3, 4]), array([5, 6, 7, 8]), array([ 9, 10, 11])]
part 1: [1 2 3 4]
part 2: [5 6 7 8]
part 3: [ 9 10 11]


In [ ]:
import pandas as pd
data = pd.Series([1,2,3,4,5,6,7])
print(data)


0    1
1    2
2    3
3    4
4    5
5    6
6    7
dtype: int64


In [ ]:
data = pd.DataFrame({
    "Name":["Aman","Prince","Priyanka","Rohit"],
     "Age":[25,24,25,26],
     "Salary" :[30000,50000,25000,40000]
})
print(data)

       Name  Age  Salary
0      Aman   25   30000
1    Prince   24   50000
2  Priyanka   25   25000
3     Rohit   26   40000


In [ ]:
data = pd.read_csv(r'C:\Users\DELL\Downloads\Student_details.csv - Sheet1.csv')
print(data)

       Name   Age Branch  SGPA  CGPA      Address
0     Vedant   20  AI/ML  7.77  7.75      Tilheri
1      Jatin   20  AI/ML  7.10  7.20  Madan Mahal
2  Shambhavi   21  AI/ML  7.75  7.45         RDVV
3       Urja   21  AI/ML  7.58  7.68        Ukhri
4       Yash   20    IOT  7.50  7.46   Aaga chowk


In [ ]:
print(data.head())

       Name   Age Branch  SGPA  CGPA      Address
0     Vedant   20  AI/ML  7.77  7.75      Tilheri
1      Jatin   20  AI/ML  7.10  7.20  Madan Mahal
2  Shambhavi   21  AI/ML  7.75  7.45         RDVV
3       Urja   21  AI/ML  7.58  7.68        Ukhri
4       Yash   20    IOT  7.50  7.46   Aaga chowk


In [ ]:
print(data.tail())

       Name   Age Branch  SGPA  CGPA      Address
0     Vedant   20  AI/ML  7.77  7.75      Tilheri
1      Jatin   20  AI/ML  7.10  7.20  Madan Mahal
2  Shambhavi   21  AI/ML  7.75  7.45         RDVV
3       Urja   21  AI/ML  7.58  7.68        Ukhri
4       Yash   20    IOT  7.50  7.46   Aaga chowk


In [ ]:
print(data[data["Age"]>20])

       Name   Age Branch  SGPA  CGPA Address
2  Shambhavi   21  AI/ML  7.75  7.45    RDVV
3       Urja   21  AI/ML  7.58  7.68   Ukhri


In [ ]:
data.drop("SGPA",axis=1,inplace=True)
print(data)

       Name   Age Branch  CGPA      Address
0     Vedant   20  AI/ML  7.75      Tilheri
1      Jatin   20  AI/ML  7.20  Madan Mahal
2  Shambhavi   21  AI/ML  7.45         RDVV
3       Urja   21  AI/ML  7.68        Ukhri
4       Yash   20    IOT  7.46   Aaga chowk


In [ ]:
print(data.describe())

             Age      CGPA
count   5.000000  5.000000
mean   20.400000  7.508000
std     0.547723  0.217187
min    20.000000  7.200000
25%    20.000000  7.450000
50%    20.000000  7.460000
75%    21.000000  7.680000
max    21.000000  7.750000


In [ ]:
print(data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   Name     5 non-null      object 
 1   Age      5 non-null      int64  
 2   Branch   5 non-null      object 
 3   CGPA     5 non-null      float64
 4   Address  5 non-null      object 
dtypes: float64(1), int64(1), object(3)
memory usage: 332.0+ bytes
None


In [ ]:
print(data.columns)

Index(['Name ', 'Age', 'Branch', 'CGPA', 'Address'], dtype='object')


In [ ]:
x=data.groupby("Age").mean("Age")
print(x)

      CGPA
Age       
20   7.470
21   7.565


In [ ]:
# merge = pd.merge(data1,data2,on = 'key_column')
# concat = pd.concat([data1,data2],axis=0)

In [ ]:
df = pd.read_csv(r'C:\Users\DELL\Downloads\Book(Sheet1).csv')
print(df)

NameError: name 'pd' is not defined

In [ ]:
df.columns

NameError: name 'df' is not defined

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Name      9 non-null      object 
 1   Age       9 non-null      int64  
 2   Roll no.  9 non-null      int64  
 3   CGPA      9 non-null      float64
 4   Address   9 non-null      object 
 5   Branch    9 non-null      object 
dtypes: float64(1), int64(2), object(3)
memory usage: 564.0+ bytes


In [ ]:
df.describe()

Age   Roll no.      CGPA
count   9.000000   9.000000  9.000000
mean   20.555556  51.444444  7.227778
std     0.726483  20.952990  0.383333
min    20.000000  20.000000  6.700000
25%    20.000000  33.000000  6.900000
50%    20.000000  60.000000  7.200000
75%    21.000000  70.000000  7.500000
max    22.000000  72.000000  7.800000

In [ ]:
df.head()

Name  Age  Roll no.  CGPA      Address Branch
0     Jatin    20        27  7.20  Madan Mahal   AIML
1  Shambhavi   21        60  7.45         RDVV   AIML
2     Vedant   20        70  7.60      Tilheri   AIML
3       Urja   21        68  7.50        Ukhri   AIML
4       Yash   20        72  7.10   Aaga Chowk    IOT

In [ ]:
data[data['Age']>20]

Name   Age Branch  CGPA Address
2  Shambhavi   21  AI/ML  7.45    RDVV
3       Urja   21  AI/ML  7.68   Ukhri

In [ ]:
data[data['Branch']!='AI/ML']

Name   Age Branch  CGPA     Address
4  Yash   20    IOT  7.46  Aaga chowk